import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'es' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  es: {
    'app.title': 'Singularity',
    'nav.dashboard': 'Panel',
    'nav.quotations': 'Solicitud de cotizaciones',
    'nav.controlsPricing': 'Controles pricing',
    'nav.executives': 'Ejecutivos',
    'nav.shipments': 'Envíos',
    'nav.customers': 'Clientes',
    'nav.suppliers': 'Proveedores',
    'nav.operations': 'Operaciones',
    'nav.documents': 'Documentos',
    'nav.analytics': 'Análisis',
    'nav.settings': 'Configuración',
    'auth.login': 'Iniciar sesión',
    'auth.signup': 'Registro',
    'auth.email': 'Correo electrónico',
    'auth.password': 'Contraseña',
    'auth.confirmPassword': 'Confirmar contraseña',
    'auth.loginButton': 'Inicia sesión',
    'auth.signupButton': 'Crear cuenta',
    'auth.noAccount': '¿No tienes cuenta?',
    'auth.haveAccount': '¿Ya tienes cuenta?',
    'auth.forgotPassword': '¿Olvidaste tu contraseña?',
    'auth.welcome':"Bienvenido",
    'auth.createAccount':"Crea tu cuenta",
    'header.search': 'Buscar solicitud',
    'header.logout': 'Cerrar sesión',
    'header.profile': 'Perfil',
    'quote.title': 'Nueva Solicitud de Cotización',
    'quote.save': 'Guardar',
    'quote.send': 'Enviar',
    'quote.generalData': 'Datos Generales',
    'quote.client': 'Cliente',
    'quote.isProspect': 'Es prospecto',
    'quote.isPriority': 'Es prioritaria',
    'quote.isQuote': 'Es licitación',
    'quote.requestType': 'Tipo de solicitud',
    'quote.applicant': 'Solicitante',
    'quote.created': 'Creado',
    'quote.responseDeadline': 'Límite de respuesta',
    'quote.services': 'Servicios',
    'quote.service': 'Servicio',
    'quote.operation': 'Operación',
    'quote.incoterm': 'Incoterm',
    'quote.expectedDeparture': 'Salida esperada',
    'quote.origin': 'Origen',
    'quote.destination': 'Destino',
    'quote.destinationZip': 'Código postal de destino',
    'quote.shippingType': 'Tipo de envío',
    'quote.associatedServices': 'Servicios Asociados',
    'quote.custody': 'Custodia',
    'quote.insurance': 'Seguro',
    'quote.inspection': 'Inspección',
    'quote.customsClearance': 'Despacho aduanal',
    'quote.comments': 'Comentarios',
    'quote.frequency': 'Frecuencia',
    'quote.quantity': 'Cantidad',
    'quote.unit': 'Medida',
    'quote.frequencyPeriod': 'Frecuencia',
    'quote.merchandise': 'Mercancía',
    'quote.search': 'Buscar',
    'quote.actions': 'Acciones',
    'quote.reference': 'Referencia',
    'quote.customer': 'Cliente',
    'quote.selectCustomer': 'Seleccione un cliente...',
    'quote.selectType': 'Seleccione un tipo...',
    'quote.customerCategory': 'Categoría Cliente',
    'quote.requestDate': 'Fecha solicitud',
    'quote.cancel': 'Cancelar',
    'quote.select': 'Seleccionar...',
    'quote.export': 'Exportación',
    'quote.import': 'Importación',
    'quote.selectCountry': 'Seleccionar país...',
    'quote.maneuver': 'Maniobra',
    'quote.programFrequency': 'Programar frecuencia',
    'quote.weekly': 'Semanal',
    'quote.monthly': 'Mensual',
    'quote.yearly': 'Anual',
    'quote.dangerous': 'Peligrosa',
    'quote.classification': 'Clasificación',
    'quote.stackable': 'Estibable',
    'quote.totalVolume': 'Volumen total',
    'quote.totalWeight': 'Peso total',
    'quote.yes': 'Sí',
    'quote.no': 'No',
    'quote.refrigerated': 'Refrigerada',
    'quote.general': 'General',
    'quote.copy': 'Copiar',
    'quote.delete': 'Eliminar',
    'quote.view': 'Ver',
    'quote.addMerchandise': 'Agregar mercancía',
    'quote.addService': 'Agregar Servicio',
    'quote.executiveAssignment': 'Asignación de Ejecutivos',
    'quote.executive': 'Ejecutivo',
    'quote.addExecutive': 'Agregar ejecutivo',
    'quote.isStackable': 'Es estibable',
    'quote.merchandiseDescription': 'Descripción de mercancía',
    'quote.merchandiseClassification': 'Clasificación de la mercancía',
    'quote.oversized': 'Sobredimensionada',
    'quote.temperature': 'Temperatura',
    'quote.bulk': 'Granel',
    'quote.addPackaging': 'Agregar embalaje',
    'quote.packaging': 'Embalaje',
    'quote.length': 'Largo',
    'quote.height': 'Alto',
    'quote.width': 'Ancho',
    'quote.weight': 'Peso',
    'quote.packagingType': 'Tipo de embalaje',
    'quote.box': 'Caja',
    'quote.bundle': 'Bulto',
    'quote.pallet': 'Palet',
    'quote.container': 'Contenedor',
    'quote.drum': 'Tambor',
    'quote.sack': 'Saco',
    'quote.add': 'Agregar',
    'quote.continue': 'Continuar',
    'quote.selectExecutive': 'Seleccionar Ejecutivo',
    'quote.allExecutivesAdded': 'Todos los ejecutivos disponibles ya han sido agregados',
    'quote.saving': 'Guardando...',
    'quote.viewTitle': 'Ver Cotización',
    'quote.editTitle': 'Editar solicitud',
    'quote.kilos': 'Kilos',
    'quote.tons': 'Toneladas',
    'quote.containers': 'Contenedores',
    'quote.refineSearch': 'Refina tu búsqueda',
    'quote.operationType': 'Tipo operación',
    'quote.requestingExecutive': 'Ejecutivo solicitante',
    'quote.all': 'Todos',
    'quote.onlyMe': 'Solo yo',
    'quote.assignmentDate': 'Fecha de asignación',
    'quote.today': 'Hoy',
    'quote.yesterday': 'Ayer',
    'quote.lessThan5Days': 'Menos de 5 días',
    'quote.lessThan30Days': 'Menos de 30 días',
    'quote.lessThan365Days': 'Menos de 365 días',
    'quote.restore': 'Restaurar',
    'quote.done': 'Hecho',
    'quote.quotationRequest': 'Solicitud de cotizaciones',
    'quote.newRequest': 'Nueva solicitud',
    'quote.refresh': 'Actualizar',
    'quote.advancedFilters': 'Filtros avanzados',
    'quote.searchCustomer': 'Buscar Cliente',
    'quote.unassigned': 'Sin asignar',
    'quote.servicesAttended': 'Servicios atendidos',
    'quote.errors.loadCatalogs': 'Error al cargar los catálogos',
    'quote.errors.loadQuotation': 'Error al cargar la cotización',
    'quote.errors.loadQuotations': 'Error al cargar las cotizaciones',
    'quote.errors.updateStatus': 'Error al actualizar el estado de la cotización',
    'quote.errors.saveQuotation': 'Error al guardar la cotización',
    'quote.errors.requestTypeNotFound': 'Error: No se pudo encontrar el tipo de solicitud seleccionado',
    'quote.warnings.merchandiseName': 'Por favor ingresa el nombre de la mercancía',
    'quote.warnings.requiredFields': 'Por favor completa los campos requeridos',
    'quote.success.updated': 'Cotización actualizada exitosamente',
    'quote.success.created': 'Cotización creada exitosamente',
    'quote.success.statusUpdated': 'Cotización {status} exitosamente',
    'quote.confirmDelete': '¿Estás seguro de eliminar esta cotización?',
    'quote.edit': 'Editar',
    'quote.noQuotations': 'No hay solicitudes de cotización',
    'quote.noResultsFilters': 'No se encontraron resultados con los filtros aplicados',
    'quote.startNewQuotation': 'Comienza creando una nueva solicitud de cotización',
    'quote.noServicesTitle': 'Sin servicios',
    'quote.noServicesMessage': 'Completa los datos de servicios.',
    'quote.noExecutivesTitle': 'Sin ejecutivos asignados',
    'quote.noExecutivesMessage': 'No has asignado ejecutivos. ¿Deseas continuar de todos modos?',
    'quote.doorToDoor': 'Door to Door',
    'quote.portToPort': 'Puerto a Puerto',
    'quote.doorToPort': 'Door to Port',
    'quote.portToDoor': 'Port to Door',
    'quote.merchandiseModal': 'Mercancía',
    'quote.dangerousClass': 'Peligrosa',
    'quote.refrigeratedClass': 'Refrigerada',
    'quote.oversizedClass': 'Sobredimensionada',
    'quote.bulkClass': 'Granel',
    'quote.generalClass': 'General',
    'quote.imo': 'IMO',
    'quote.un': 'UN',
    'quote.selectOption': 'Seleccionar',
    'quote.packagingTable.packaging': 'EMBALAJE',
    'quote.packagingTable.quantity': 'CANTIDAD',
    'quote.packagingTable.length': 'LARGO',
    'quote.packagingTable.height': 'ALTO',
    'quote.packagingTable.width': 'ANCHO',
    'quote.packagingTable.weight': 'PESO',
    'quote.units.lbsInches': 'Lbs/Pulgadas',
    'quote.units.kgCm': 'Kgm/Cm',
    'quote.addPackagingModal': 'Agregar Embalaje',
    'quote.cm': 'cm',
    'quote.plg': 'plg',
    'quote.kg': 'kg',
    'quote.lbs': 'lbs',
    'quote.selectClient': 'Seleccione un cliente...',
    'quote.isBid': 'Es licitación',
    'exec.title': 'Gestión de Ejecutivos',
    'exec.newExecutive': 'Nuevo Ejecutivo',
    'exec.editExecutive': 'Editar Ejecutivo',
    'exec.save': 'Guardar',
    'exec.cancel': 'Cancelar',
    'exec.delete': 'Eliminar',
    'exec.actions': 'Acciones',
    'exec.search': 'Buscar por nombre, apellido, nómina o email...',
    'exec.filterAll': 'Todos',
    'exec.filterActive': 'Activos',
    'exec.filterInactive': 'Inactivos',
    'exec.nombre': 'Nombre',
    'exec.apellidoPaterno': 'Apellido Paterno',
    'exec.apellidoMaterno': 'Apellido Materno',
    'exec.numeroNomina': 'Número de Nómina',
    'exec.fechaIngreso': 'Fecha de Ingreso',
    'exec.email': 'Correo Electrónico',
    'exec.departamento': 'Departamento',
    'exec.activo': 'Activo',
    'exec.disponible': 'Disponible',
    'exec.noDisponible': 'No Disponible',
    'exec.generalData': 'Datos del Ejecutivo',
    'exec.noResults': 'No se encontraron ejecutivos',
    'exec.confirmDelete': '¿Está seguro que desea eliminar este ejecutivo?',
    'exec.successSave': 'Ejecutivo guardado exitosamente',
    'exec.successDelete': 'Ejecutivo eliminado exitosamente',
    'exec.errorSave': 'Error al guardar el ejecutivo',
    'exec.errorDelete': 'Error al eliminar el ejecutivo',
    'exec.errorLoad': 'Error al cargar los ejecutivos',
    'exec.nominaExists': 'El número de nómina ya existe',
    'exec.invalidEmail': 'Email inválido',
    'exec.requiredFields': 'Por favor complete todos los campos requeridos',
    'cust.title': 'Catálogo de Clientes',
    'cust.newCustomer': 'Nuevo Cliente',
    'cust.editCustomer': 'Editar Cliente',
    'cust.save': 'Guardar',
    'cust.cancel': 'Cancelar',
    'cust.delete': 'Eliminar',
    'cust.search': 'Buscar Cliente',
    'cust.generalData': 'Datos Generales',
    'cust.addresses': 'Domicilio',
    'cust.contacts': 'Contactos',
    'cust.isBranch': 'Es Sucursal',
    'cust.branchName': 'Nombre de Sucursal',
    'cust.type': 'Tipo Persona',
    'cust.fisica': 'Física',
    'cust.moral': 'Moral',
    'cust.selectPerson': 'Seleccionar Persona',
    'cust.selectCompany': 'Seleccionar Empresa',
    'cust.newPerson': 'Nueva Persona',
    'cust.newCompany': 'Nueva Empresa',
    'cust.nationality': 'Nacionalidad',
    'cust.nacional': 'Nacional',
    'cust.extranjero': 'Extranjero',
    'cust.fiscalData': 'Datos Fiscales',
    'cust.businessName': 'Razón Social / IMP / EXP',
    'cust.taxId': 'RFC',
    'cust.country': 'País',
    'cust.state': 'Estado',
    'cust.personName': 'Nombre',
    'cust.birthDate': 'Fecha de Nacimiento',
    'cust.companyName': 'Nombre Empresa',
    'cust.rfc': 'RFC',
    'cust.addContact': 'Agregar Contacto',
    'cust.contactType': 'Tipo',
    'cust.contactName': 'Nombre',
    'cust.contactEmail': 'Email',
    'cust.contactPhone': 'Teléfono',
    'cust.contactPosition': 'Puesto',
    'cust.addAddress': 'Agregar Domicilio',
    'cust.street': 'Calle',
    'cust.city': 'Ciudad',
    'cust.postalCode': 'Código Postal',
    'cust.useRegistered': 'Utilizar datos Registrados',
    'cust.fiscalAddress': 'Domicilio Fiscal',
    'cust.noResults': 'No se encontraron clientes',
    'cust.successSave': 'Cliente guardado exitosamente',
    'cust.successDelete': 'Cliente eliminado exitosamente',
    'cust.errorSave': 'Error al guardar el cliente',
    'cust.errorDelete': 'Error al eliminar el cliente',
    'cust.errorLoad': 'Error al cargar los clientes',
    'cust.enabled': 'Habilitado',
    'cust.actions': 'Acciones',
    'supp.title': 'Proveedores',
    'supp.newSupplier': 'Nuevo Proveedor',
    'supp.search' : 'Buscar Proveedor',
    'supp.generalData': 'Datos Generales',
    'supp.noResults': 'No se encontraron proveedores',
    'supp.errorSave': 'Error al guardar el proveedor',
    'supp.errorDelete': 'Error al eliminar el proveedor',
    'nav.catalogs': 'Catálogos',
    'nav.catalogs.imo': 'IMO',
    'nav.catalogs.incoterms': 'Incoterms',
    'nav.catalogs.services': 'Servicios',
    'nav.catalogs.status': 'Estatus',
    'nav.catalogs.requestTypes': 'Tipos de Solicitud',
    'nav.catalogs.countries': 'Países',
    'nav.catalogs.sectorOfBusiness': 'Sector de negocios',
    'catalog.title': 'Catálogo de {name}',
    'catalog.new': 'Nuevo {name}',
    'catalog.edit': 'Editar {name}',
    'catalog.save': 'Guardar',
    'catalog.cancel': 'Cancelar',
    'catalog.delete': 'Eliminar',
    'catalog.search': 'Buscar...',
    'catalog.actions': 'Acciones',
    'catalog.noResults': 'No se encontraron resultados',
    'catalog.confirmDelete': '¿Está seguro que desea eliminar este registro?',
    'catalog.successSave': 'Registro guardado exitosamente',
    'catalog.successDelete': 'Registro eliminado exitosamente',
    'catalog.errorSave': 'Error al guardar el registro',
    'catalog.errorDelete': 'Error al eliminar el registro',
    'catalog.errorLoad': 'Error al cargar los datos',
    'catalog.imo.code': 'Código IMO',
    'catalog.imo.description': 'Descripción',
    'catalog.incoterm.code': 'Incoterm',
    'catalog.service.name': 'Nombre del Servicio',
    'catalog.service.category': 'Categoría',
    'catalog.service.categoryMain': 'Principal',
    'catalog.service.categoryAccessory': 'Accesorio',
    'catalog.service.email': 'Email',
    'catalog.requestType.name': 'Tipo de Solicitud',
    'catalog.status.category': 'Categoría',
    'catalog.status.subcategory': 'Subcategoría',
    'catalog.status.code': 'Código',
    'catalog.status.name': 'Nombre',
    'catalog.status.description': 'Descripción',
    'catalog.status.active': 'Activo',
    'catalog.filterAll': 'Todos',
    'catalog.filterActive': 'Activos',
    'catalog.filterInactive': 'Inactivos',
    'catalog.country.code': 'Código País',
    'catalog.country.name': 'Nombre del País',
    'catalog.sectorOfBusiness.code': 'Nombre del Sector',
    'catalog.sectorOfBusiness.description': 'Descripción',
    'ctrlpricing.title': 'Control de pricing',
    'ctrlpricing.refresh': 'Actualizar',
    'ctrlpricing.filtro': 'Filtros',
    'ctrlpricing.actions': 'Acciones',
    'ctrlpricing.search': 'Buscar solicitud',
    'ctrlpricing.edit': 'Editar',
    'ctrlpricing.delete': 'Eliminar',
    'ctrlpricing.addcontrol': 'Agregar número de control',
    'ctrlpricing.norequests': 'No hay solicitudes disponibles',
    'ctrlpricing.noresults': 'No se encontraron resultados con los filtros aplicados',
    'ctrlpricing.noresultsstatus': 'No hay solicitudes con estado mayor o igual a 3',
    'ctrlpricing.servicesattended': 'Servicios atendidos',
    'ctrlpricing.unassigned': 'Sin asignar',
    'ctrlpricing.editcontrolnumber': 'Editar número de control',
    'ctrlpricing.newcontrolnumber': 'Nuevo número de control',
    'ctrlpricing.save': 'Guardar',
    'ctrlpricing.export': 'Exportar',
    'ctrlpricing.duplicate': 'Duplicar',
    'ctrlpricing.historical': 'Historial',
    'ctrlpricing.priority': 'Prioridad',
    'ctrlpricing.bidding': 'Licitación',
    'ctrlpricing.decline': 'Declinar',
    'ctrlpricing.quoted': 'Cotizada',
    'ctrlpricing.supplierassignment': 'Asignación de proveedores',
    'ctrlpricing.supplier': 'Proveedor',
    'ctrlpricing.suppliername': 'Nombre del proveedor',
    'ctrlpricing.addsupplier': 'Agregar proveedor',
    'ctrlpricing.status': 'Estatus',
    'ctrlpricing.network': 'Red / Alianza',
    'ctrlpricing.complexity': 'Complejidad',
    'ctrlpricing.currency': 'Moneda',
    'ctrlpricing.unitprofit': 'Profit Unitario',
    'ctrlpricing.volume': 'Volumen',
    'ctrlpricing.generalprofit': 'Profit general',
    'ctrlpricing.comments': 'Comentarios',
    'ctrlpricing.services': 'Servicios',
    'ctrlpricing.serviceincluded': 'Servicio incluido',
    'ctrlpricing.alreadyused': 'Ya usado en otro control',
    'ctrlpricing.includeservice': 'Incluir servicio',
    'ctrlpricing.service': 'Servicio',
    'ctrlpricing.operation': 'Operación',
    'ctrlpricing.expecteddeparture': 'Salida esperada',
    'ctrlpricing.origin': 'Origen',
    'ctrlpricing.destination': 'Destino',
    'ctrlpricing.cp': 'Código postal de destino',
    'ctrlpricing.shippingtype': 'Tipo de envío',
    'ctrlpricing.associatedServices': 'Servicios Asociados',
    'ctrlpricing.noassociatedservices': 'Sin servicios asociados',
    'ctrlpricing.nocomments': 'Sin comentarios',
    'ctrlpricing.programFrequency': 'Programar frecuencia',
    'ctrlpricing.frequency': 'Frecuencia',
    'ctrlpricing.quantity': 'Cantidad',
    'ctrlpricing.unit': 'Medida',
    'ctrlpricing.commodity': 'MERCANCÍA',
    'ctrlpricing.dangerous': 'PELIGROSA',
    'ctrlpricing.classification': 'CLASIFICACIÓN',
    'ctrlpricing.stackable': 'ESTIBABLE',
    'ctrlpricing.totalVolume': 'VOL. TOTAL',
    'ctrlpricing.totalWeight': 'PESO TOTAL',
    'ctrlpricing.refineSearch': 'Refina tu búsqueda',
    'ctrlpricing.requestdate': 'Fecha de solicitud',
    'ctrlpricing.today': 'HOY',
    'ctrlpricing.yesterday': 'AYER',
    'ctrlpricing.less5days': 'MENOS DE 5 DÍAS',
    'ctrlpricing.less30days': 'MENOS DE 30 DÍAS',
    'ctrlpricing.less365days': 'MENOS DE 365 DÍAS',
    'ctrlpricing.assignedexecutive': 'Ejecutivo asignado',
    'ctrlpricing.all': 'TODOS',
    'ctrlpricing.onlyme': 'SOLO YO',
    'ctrlpricing.select': 'SELECCIONAR',
    'ctrlpricing.selectexecutive': 'Seleccionar ejecutivo...',

  },
  en: {
    'app.title': 'Singularity',
    'nav.dashboard': 'Dashboard',
    'nav.quotations': 'Quotation Request',
    'nav.controlsPricing': 'Pricing Controls',
    'nav.executives': 'Executives',
    'nav.shipments': 'Shipments',
    'nav.customers': 'Customers',
    'nav.suppliers': 'Suppliers',
    'nav.operations': 'Operations',
    'nav.documents': 'Documents',
    'nav.analytics': 'Analytics',
    'nav.settings': 'Settings',
    'auth.login': 'Sign In',
    'auth.signup': 'Sign Up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.loginButton': 'Sign In',
    'auth.signupButton': 'Create Account',
    'auth.noAccount': "Don't have an account?",
    'auth.haveAccount': 'Already have an account?',
    'auth.forgotPassword': 'Forgot your password?',
    'auth.welcome':"Welcome back",
    'auth.createAccount':"Create your account",
    'header.search': 'Search request',
    'header.logout': 'Sign Out',
    'header.profile': 'Profile',
    'quote.title': 'New Quotation Request',
    'quote.save': 'Save',
    'quote.send': 'Send',
    'quote.generalData': 'General Data',
    'quote.client': 'Client',
    'quote.isProspect': 'Is prospect',
    'quote.isPriority': 'Is priority',
    'quote.isQuote': 'Is tender',
    'quote.requestType': 'Request type',
    'quote.applicant': 'Applicant',
    'quote.created': 'Created',
    'quote.responseDeadline': 'Response deadline',
    'quote.services': 'Services',
    'quote.service': 'Service',
    'quote.operation': 'Operation',
    'quote.incoterm': 'Incoterm',
    'quote.expectedDeparture': 'Expected departure',
    'quote.origin': 'Origin',
    'quote.destination': 'Destination',
    'quote.destinationZip': 'Destination zip code',
    'quote.shippingType': 'Shipping type',
    'quote.associatedServices': 'Associated Services',
    'quote.custody': 'Custody',
    'quote.insurance': 'Insurance',
    'quote.inspection': 'Inspection',
    'quote.customsClearance': 'Customs clearance',
    'quote.comments': 'Comments',
    'quote.frequency': 'Frequency',
    'quote.quantity': 'Quantity',
    'quote.unit': 'Unit',
    'quote.frequencyPeriod': 'Frequency',
    'quote.merchandise': 'Merchandise',
    'quote.search': 'Search',
    'quote.actions': 'Actions',
    'quote.reference': 'Reference',
    'quote.customer': 'Customer',
    'quote.selectCustomer': 'Select a customer...',
    'quote.selectType': 'Select a type...',
    'quote.customerCategory': 'Customer Category',
    'quote.requestDate': 'Request date',
    'quote.cancel': 'Cancel',
    'quote.select': 'Select...',
    'quote.export': 'Export',
    'quote.import': 'Import',
    'quote.selectCountry': 'Select country...',
    'quote.maneuver': 'Maneuver',
    'quote.programFrequency': 'Program frequency',
    'quote.weekly': 'Weekly',
    'quote.monthly': 'Monthly',
    'quote.yearly': 'Yearly',
    'quote.dangerous': 'Dangerous',
    'quote.classification': 'Classification',
    'quote.stackable': 'Stackable',
    'quote.totalVolume': 'Total volume',
    'quote.totalWeight': 'Total weight',
    'quote.yes': 'Yes',
    'quote.no': 'No',
    'quote.refrigerated': 'Refrigerated',
    'quote.general': 'General',
    'quote.copy': 'Copy',
    'quote.delete': 'Delete',
    'quote.view': 'View',
    'quote.addMerchandise': 'Add merchandise',
    'quote.addService': 'Add Service',
    'quote.executiveAssignment': 'Executive Assignment',
    'quote.executive': 'Executive',
    'quote.addExecutive': 'Add executive',
    'quote.isStackable': 'Is stackable',
    'quote.merchandiseDescription': 'Merchandise description',
    'quote.merchandiseClassification': 'Merchandise classification',
    'quote.oversized': 'Oversized',
    'quote.temperature': 'Temperature',
    'quote.bulk': 'Bulk',
    'quote.addPackaging': 'Add packaging',
    'quote.packaging': 'Packaging',
    'quote.length': 'Length',
    'quote.height': 'Height',
    'quote.width': 'Width',
    'quote.weight': 'Weight',
    'quote.packagingType': 'Packaging type',
    'quote.box': 'Box',
    'quote.bundle': 'Bundle',
    'quote.pallet': 'Pallet',
    'quote.container': 'Container',
    'quote.drum': 'Drum',
    'quote.sack': 'Sack',
    'quote.add': 'Add',
    'quote.continue': 'Continue',
    'quote.selectExecutive': 'Select Executive',
    'quote.allExecutivesAdded': 'All available executives have been added',
    'quote.saving': 'Saving...',
    'quote.viewTitle': 'View Quotation',
    'quote.editTitle': 'Edit request',
    'quote.kilos': 'Kilos',
    'quote.tons': 'Tons',
    'quote.containers': 'Containers',
    'quote.refineSearch': 'Refine your search',
    'quote.operationType': 'Operation type',
    'quote.requestingExecutive': 'Requesting executive',
    'quote.all': 'All',
    'quote.onlyMe': 'Only me',
    'quote.assignmentDate': 'Assignment date',
    'quote.today': 'Today',
    'quote.yesterday': 'Yesterday',
    'quote.lessThan5Days': 'Less than 5 days',
    'quote.lessThan30Days': 'Less than 30 days',
    'quote.lessThan365Days': 'Less than 365 days',
    'quote.restore': 'Restore',
    'quote.done': 'Done',
    'quote.quotationRequest': 'Quotation Request',
    'quote.newRequest': 'New request',
    'quote.refresh': 'Refresh',
    'quote.advancedFilters': 'Advanced filters',
    'quote.searchCustomer': 'Search Customer',
    'quote.unassigned': 'Unassigned',
    'quote.servicesAttended': 'Services attended',
    'quote.errors.loadCatalogs': 'Error loading catalogs',
    'quote.errors.loadQuotation': 'Error loading quotation',
    'quote.errors.loadQuotations': 'Error loading quotations',
    'quote.errors.updateStatus': 'Error updating quotation status',
    'quote.errors.saveQuotation': 'Error saving quotation',
    'quote.errors.requestTypeNotFound': 'Error: Could not find the selected request type',
    'quote.warnings.merchandiseName': 'Please enter the merchandise name',
    'quote.warnings.requiredFields': 'Please complete the required fields',
    'quote.success.updated': 'Quotation updated successfully',
    'quote.success.created': 'Quotation created successfully',
    'quote.success.statusUpdated': 'Quotation {status} successfully',
    'quote.confirmDelete': 'Are you sure you want to delete this quotation?',
    'quote.edit': 'Edit',
    'quote.noQuotations': 'No quotation requests',
    'quote.noResultsFilters': 'No results found with the applied filters',
    'quote.startNewQuotation': 'Start by creating a new quotation request',
    'quote.noServicesTitle': 'No services',
    'quote.noServicesMessage': 'You have not added any services. Do you want to continue anyway?',
    'quote.noExecutivesTitle': 'No executives assigned',
    'quote.noExecutivesMessage': 'You have not assigned any executives. Do you want to continue anyway?',
    'quote.doorToDoor': 'Door to Door',
    'quote.portToPort': 'Port to Port',
    'quote.doorToPort': 'Door to Port',
    'quote.portToDoor': 'Port to Door',
    'quote.merchandiseModal': 'Merchandise',
    'quote.dangerousClass': 'Dangerous',
    'quote.refrigeratedClass': 'Refrigerated',
    'quote.oversizedClass': 'Oversized',
    'quote.bulkClass': 'Bulk',
    'quote.generalClass': 'General',
    'quote.imo': 'IMO',
    'quote.un': 'UN',
    'quote.selectOption': 'Select',
    'quote.packagingTable.packaging': 'PACKAGING',
    'quote.packagingTable.quantity': 'QUANTITY',
    'quote.packagingTable.length': 'LENGTH',
    'quote.packagingTable.height': 'HEIGHT',
    'quote.packagingTable.width': 'WIDTH',
    'quote.packagingTable.weight': 'WEIGHT',
    'quote.units.lbsInches': 'Lbs/Inches',
    'quote.units.kgCm': 'Kg/Cm',
    'quote.addPackagingModal': 'Add Packaging',
    'quote.cm': 'cm',
    'quote.plg': 'in',
    'quote.kg': 'kg',
    'quote.lbs': 'lbs',
    'quote.selectClient': 'Select a client...',
    'quote.isBid': 'Is bidding',
    'exec.title': 'Executive Management',
    'exec.newExecutive': 'New Executive',
    'exec.editExecutive': 'Edit Executive',
    'exec.save': 'Save',
    'exec.cancel': 'Cancel',
    'exec.delete': 'Delete',
    'exec.actions': 'Actions',
    'exec.search': 'Search by name, surname, employee ID or email...',
    'exec.filterAll': 'All',
    'exec.filterActive': 'Active',
    'exec.filterInactive': 'Inactive',
    'exec.nombre': 'First Name',
    'exec.apellidoPaterno': 'Last Name',
    'exec.apellidoMaterno': 'Second Last Name',
    'exec.numeroNomina': 'Employee ID',
    'exec.fechaIngreso': 'Hire Date',
    'exec.email': 'Email Address',
    'exec.departamento': 'Department',
    'exec.activo': 'Active',
    'exec.disponible': 'Available',
    'exec.noDisponible': 'Not Available',
    'exec.generalData': 'Executive Information',
    'exec.noResults': 'No executives found',
    'exec.confirmDelete': 'Are you sure you want to delete this executive?',
    'exec.successSave': 'Executive saved successfully',
    'exec.successDelete': 'Executive deleted successfully',
    'exec.errorSave': 'Error saving executive',
    'exec.errorDelete': 'Error deleting executive',
    'exec.errorLoad': 'Error loading executives',
    'exec.nominaExists': 'Employee ID already exists',
    'exec.invalidEmail': 'Invalid email',
    'exec.requiredFields': 'Please fill in all required fields',
    'cust.title': 'Customer Catalog',
    'cust.newCustomer': 'New Customer',
    'cust.editCustomer': 'Edit Customer',
    'cust.save': 'Save',
    'cust.cancel': 'Cancel',
    'cust.delete': 'Delete',
    'cust.search': 'Search Customer',
    'cust.generalData': 'General Data',
    'cust.addresses': 'Addresses',
    'cust.contacts': 'Contacts',
    'cust.isBranch': 'Is Branch',
    'cust.branchName': 'Branch Name',
    'cust.type': 'Person Type',
    'cust.fisica': 'Individual',
    'cust.moral': 'Company',
    'cust.selectPerson': 'Select Person',
    'cust.selectCompany': 'Select Company',
    'cust.newPerson': 'New Person',
    'cust.newCompany': 'New Company',
    'cust.nationality': 'Nationality',
    'cust.nacional': 'National',
    'cust.extranjero': 'Foreign',
    'cust.fiscalData': 'Fiscal Data',
    'cust.businessName': 'Business Name / IMP / EXP',
    'cust.taxId': 'Tax ID',
    'cust.country': 'Country',
    'cust.state': 'State',
    'cust.personName': 'Name',
    'cust.birthDate': 'Birth Date',
    'cust.companyName': 'Company Name',
    'cust.rfc': 'Tax ID',
    'cust.addContact': 'Add Contact',
    'cust.contactType': 'Type',
    'cust.contactName': 'Name',
    'cust.contactEmail': 'Email',
    'cust.contactPhone': 'Phone',
    'cust.contactPosition': 'Position',
    'cust.addAddress': 'Add Address',
    'cust.street': 'Street',
    'cust.city': 'City',
    'cust.postalCode': 'Postal Code',
    'cust.useRegistered': 'Use Registered Data',
    'cust.fiscalAddress': 'Fiscal Address',
    'cust.noResults': 'No customers found',
    'cust.successSave': 'Customer saved successfully',
    'cust.successDelete': 'Customer deleted successfully',
    'cust.errorSave': 'Error saving customer',
    'cust.errorDelete': 'Error deleting customer',
    'cust.errorLoad': 'Error loading customers',
    'cust.enabled': 'Enabled',
    'cust.actions': 'Actions',
    'supp.title': 'Suppliers',
    'supp.newSupplier': 'New Supplier',
    'supp.search' : 'Search Supplier',
    'supp.generalData': 'General Data',
    'supp.noResults': 'No supplier found',
    'supp.errorSave': 'Error saving supplier',
    'supp.errorDelete': 'Error deleting supplier',
    'nav.catalogs': 'Catalogs',
    'nav.catalogs.imo': 'IMO',
    'nav.catalogs.incoterms': 'Incoterms',
    'nav.catalogs.services': 'Services',
    'nav.catalogs.status': 'Status',
    'nav.catalogs.requestTypes': 'Request Types',
    'nav.catalogs.countries': 'Countries',
    'nav.catalogs.sectorOfBusiness': 'Sector of Business',
    'catalog.title': '{name} Catalog',
    'catalog.new': 'New {name}',
    'catalog.edit': 'Edit {name}',
    'catalog.save': 'Save',
    'catalog.cancel': 'Cancel',
    'catalog.delete': 'Delete',
    'catalog.search': 'Search...',
    'catalog.actions': 'Actions',
    'catalog.noResults': 'No results found',
    'catalog.confirmDelete': 'Are you sure you want to delete this record?',
    'catalog.successSave': 'Record saved successfully',
    'catalog.successDelete': 'Record deleted successfully',
    'catalog.errorSave': 'Error saving record',
    'catalog.errorDelete': 'Error deleting record',
    'catalog.errorLoad': 'Error loading data',
    'catalog.imo.code': 'IMO Code',
    'catalog.imo.description': 'Description',
    'catalog.incoterm.code': 'Incoterm',
    'catalog.service.name': 'Service Name',
    'catalog.service.category': 'Category',
    'catalog.service.categoryMain': 'Main',
    'catalog.service.categoryAccessory': 'Accessory',
    'catalog.service.email': 'Email',
    'catalog.requestType.name': 'Request Type',
    'catalog.status.category': 'Category',
    'catalog.status.subcategory': 'Subcategory',
    'catalog.status.code': 'Code',
    'catalog.status.name': 'Name',
    'catalog.status.description': 'Description',
    'catalog.status.active': 'Active',
    'catalog.filterAll': 'All',
    'catalog.filterActive': 'Active',
    'catalog.filterInactive': 'Inactive',
    'catalog.country.code': 'Country Code',
    'catalog.country.name': 'Country Name',
    'catalog.sectorOfBusiness.code': 'Sector Name',
    'catalog.sectorOfBusiness.description': 'Description',
    'ctrlpricing.title': 'Pricing controls',
    'ctrlpricing.refresh': 'Refresh',
    'ctrlpricing.filtro': 'Filters',
    'ctrlpricing.actions': 'Actions',
    'ctrlpricing.search': 'Search request',
    'ctrlpricing.edit': 'Edit',
    'ctrlpricing.delete': 'Delete',
    'ctrlpricing.addcontrol': 'Add control number',
    'ctrlpricing.norequests': 'No requests available',
    'ctrlpricing.noresults': 'No results were found with the filters applied.',
    'ctrlpricing.noresultsstatus': 'There are no requests with a status greater than or equal to 3',
    'ctrlpricing.servicesattended': 'Services attended',
    'ctrlpricing.unassigned': 'Unassigned',
    'ctrlpricing.editcontrolnumber': 'Edit control number',
    'ctrlpricing.newcontrolnumber': 'New control number',
    'ctrlpricing.save': 'Save',
    'ctrlpricing.export': 'Export', 
    'ctrlpricing.duplicate': 'Duplicate',
    'ctrlpricing.historical': 'Historical',
    'ctrlpricing.priority': 'Priority',
    'ctrlpricing.bidding': 'Bidding',
    'ctrlpricing.decline': 'Decline',
    'ctrlpricing.quoted': 'Quoted',
    'ctrlpricing.supplierassignment': 'Supplier assignment',
    'ctrlpricing.supplier': 'Supplier',
    'ctrlpricing.suppliername': 'Supplier name',
    'ctrlpricing.addsupplier': 'Add supplier',
    'ctrlpricing.status': 'Status',
    'ctrlpricing.network': 'Network / Alliance',
    'ctrlpricing.complexity': 'Complexity',
    'ctrlpricing.currency': 'Currency',
    'ctrlpricing.unitprofit': 'Unit Profit',
    'ctrlpricing.volume': 'Volume',
    'ctrlpricing.generalprofit': 'General profit',
    'ctrlpricing.comments': 'Comments',
    'ctrlpricing.services': 'Services',
    'ctrlpricing.serviceincluded': 'Service included',
    'ctrlpricing.alreadyused': 'Already used in another controller',
    'ctrlpricing.includeservice': 'Include service',
    'ctrlpricing.service': 'Service',
    'ctrlpricing.operation': 'Operation',
    'ctrlpricing.expecteddeparture': 'Expected departure',
    'ctrlpricing.origin': 'Origin',
    'ctrlpricing.destination': 'Destination',
    'ctrlpricing.cp': 'Destination zip code',
    'ctrlpricing.shippingtype': 'Shipping type',
    'ctrlpricing.associatedServices': 'Associated Services',
    'ctrlpricing.noassociatedservices': 'No associated services',
    'ctrlpricing.nocomments': 'No comments',
    'ctrlpricing.programFrequency': 'Schedule frequency',
    'ctrlpricing.frequency': 'Frequency',
    'ctrlpricing.quantity': 'Quantity',
    'ctrlpricing.unit': 'Unit',
    'ctrlpricing.commodity': 'COMMODITY',
    'ctrlpricing.dangerous': 'DANGEROUS',
    'ctrlpricing.classification': 'CLASSIFICATION',
    'ctrlpricing.stackable': 'STACKABLE',
    'ctrlpricing.totalVolume': 'TOTAL VOL',
    'ctrlpricing.totalWeight': 'TOTAL WEIGHT',
    'ctrlpricing.refineSearch': 'Refine your search',
    'ctrlpricing.requestdate': 'Request date',
        'ctrlpricing.today': 'TODAY',
    'ctrlpricing.yesterday': 'YESTERDAY',
    'ctrlpricing.less5days': 'LESS 5 DAYS',
    'ctrlpricing.less30days': 'LESS 30 DAYS',
    'ctrlpricing.less365days': 'LESS 365 DAYS',
    'ctrlpricing.assignedexecutive': 'Assigned executive',
    'ctrlpricing.all': 'ALL',
    'ctrlpricing.onlyme': 'ONLY ME',
    'ctrlpricing.select': 'SELECT',
    'ctrlpricing.selectexecutive': 'Select executive...',
  },
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('es');
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    const stored = localStorage.getItem('language') as Language | null;
    if (stored) {
      setLanguage(stored);
    }
    setMounted(true);
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['es']] || key;
  };

  if (!mounted) return <>{children}</>;

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
