import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'es' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (
    key: string,
    params?: {
      values?: Record<string, string | number>;
      upper?: boolean;
    }
  ) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  es: {
    'app.title': 'Singularity',
    'app.loading': "Cargando",
    'nav.dashboard': 'Panel',
    'nav.quotations': 'Solicitud de cotizaciones',
    'nav.controlsPricing': 'Controles pricing',
    'nav.trackingMonitor': 'Monitor de rastreo',
    'nav.executives': 'Ejecutivos',
    'nav.shipments': 'Envíos',
    'nav.customers': 'Clientes',
    'nav.companies': 'Empresas',
    'nav.suppliers': 'Proveedores',
    'nav.operations': 'Operaciones',
    'nav.documents': 'Documentos',
    'nav.analytics': 'Análisis',
    'nav.settings': 'Configuración',
    'nav.reports': 'Reportes',
    'nav.digitization': 'Digitalización',
    'auth.login': 'Iniciar sesión',
    'auth.signup': 'Registro',
    'auth.email': 'Correo electrónico',
    'auth.password': 'Contraseña',
    'auth.confirmPassword': 'Confirmar contraseña',
    'auth.loginButton': 'Inicia sesión',
    'auth.signupButton': 'Crear cuenta',
    'auth.noAccount': '¿No tienes cuenta?',
    'auth.haveAccount': '¿Ya tienes cuenta?',
    'auth.forgotPassword': '¿Olvidaste tu contraseña?',
    'auth.welcome':"Bienvenido",
    'auth.createAccount':"Crea tu cuenta",
    'header.search': 'Buscar solicitud',
    'header.logout': 'Cerrar sesión',
    'header.profile': 'Perfil',
    'quote.title': 'Nueva solicitud de cotización',
    'quote.save': 'Guardar',
    'quote.sendForQuote': 'Enviar a cotizar',
    'quote.generalData': 'Datos generales',
    'quote.client': 'Cliente',
    'quote.prospect': 'Prospecto',
    'quote.isProspect': 'Es prospecto',
    'quote.isPriority': 'Es prioritaria',
    'quote.isQuote': 'Es licitación',
    'quote.requestType': 'Tipo de solicitud',
    'quote.orderBy': 'Ordenar por',
    'quote.orderDesc': 'Descendente',
    'quote.applicant': 'Solicitante',
    'quote.created': 'Creado',
    'quote.responseDeadline': 'Límite de respuesta',
    'quote.services': 'Servicios',
    'quote.service': 'Servicio',
    'quote.operation': 'Operación',
    'quote.incoterm': 'Incoterm',
    'quote.expectedDeparture': 'Salida esperada',
    'quote.origin': 'Origen',
    'quote.originZip' : 'C.P. origen',
    'quote.originPort' : 'Puerto origen',
    'quote.originAirport' : 'Aeropuerto origen',
    'quote.destination': 'Destino',
    'quote.destinationZip': 'C.P. destino',
    'quote.destinationPort' : 'Puerto destino',
    'quote.destinationAirport' : 'Aeropuerto destino',
    'quote.shippingType': 'Tipo de envío',
    'quote.associatedServices': 'Servicios asociados',
    'quote.custody': 'Custodia',
    'quote.insurance': 'Seguro',
    'quote.inspection': 'Inspección',
    'quote.customsClearance': 'Despacho aduanal',
    'quote.warehouse': 'Almacén',
    'quote.parcelService': 'Paquetería',
    'quote.PreInspectionOrigin': 'Previo en Origen',
    'quote.comments': 'Comentarios',
    'quote.frequency': 'Frecuencia',
    'quote.quantity': 'Cantidad',
    'quote.unit': 'Medida',
    'quote.frequencyPeriod': 'Frecuencia',
    'quote.merchandise': 'Mercancía',
    'quote.search': 'Buscar por referencia, cliente o tipo de solicitud',
    'quote.actions': 'Acciones',
    'quote.reference': 'Referencia',
    'quote.customer': 'Cliente',
    'quote.selectCustomer': 'Seleccione un cliente...',
    'quote.selectType': 'Seleccione un tipo...',
    'quote.customerCategory': 'Categoría cliente',
    'quote.requestDate': 'Fecha solicitud',
    'quote.cancel': 'Cancelar',
    'quote.select': 'Seleccionar...',
    'quote.export': 'Exportación',
    'quote.import': 'Importación',
    'quote.national': 'Nacional',
    'quote.localUSA': 'Local USA',
    'quote.Triangulacion': 'Triangulación',
    'quote.selectCountry': 'Seleccionar país...',
    'quote.maneuver': 'Maniobra',
    'quote.programFrequency': 'Programar frecuencia',
    'quote.weekly': 'Semanal',
    'quote.monthly': 'Mensual',
    'quote.yearly': 'Anual',
    'quote.dangerous': 'Peligrosa',
    'quote.classification': 'Clasificación',
    'quote.stackable': 'Estibable',
    'quote.totalVolume': 'Volumen total',
    'quote.totalWeight': 'Peso total',
    'quote.volumetricWeightTotal': 'Peso volumétrico total',
    'quote.yes': 'Sí',
    'quote.no': 'No',
    'quote.refrigerated': 'Refrigerada',
    'quote.general': 'General',
    'quote.copy': 'Copiar',
    'quote.delete': 'Eliminar',
    'quote.view': 'Ver',
    'quote.addMerchandise': 'Agregar mercancía',
    'quote.addService': 'Agregar servicio',
    'quote.executiveAssignment': 'Asignación de ejecutivos',
    'quote.executive': 'Ejecutivo',
    'quote.addExecutive': 'Agregar ejecutivo',
    'quote.isStackable': 'Es estibable',
    'quote.merchandiseDescription': 'Descripción de mercancía',
    'quote.merchandiseClassification': 'Clasificación de la mercancía',
    'quote.oversized': 'Sobredimensionada',
    'quote.temperature': 'Temperatura',
    'quote.bulk': 'Granel',
    'quote.addPackaging': 'Agregar embalaje',
    'quote.packaging': 'Embalaje',
    'quote.length': 'Largo',
    'quote.height': 'Alto',
    'quote.width': 'Ancho',
    'quote.weight': 'Peso',
    'quote.packagingType': 'Tipo de embalaje',
    'quote.box': 'Caja',
    'quote.bundle': 'Bulto',
    'quote.pallet': 'Palet',
    'quote.container': 'Contenedor',
    'quote.selectcontainer': 'Selecciona un contenedor',
    'quote.allContainersAdded': 'No quedan contenedores por agregar',
    'quote.unitVolume': 'Unidad de volumen',
    'quote.unitWeight': 'Unidad de peso',
    'quote.drum': 'Tambor',
    'quote.sack': 'Saco',
    'quote.add': 'Agregar',
    'quote.continue': 'Continuar',
    'quote.selectExecutive': 'Seleccionar ejecutivo',
    'quote.allExecutivesAdded': 'Todos los ejecutivos disponibles ya han sido agregados',
    'quote.saving': 'Guardando...',
    'quote.viewTitle': 'Ver cotización',
    'quote.editTitle': 'Editar solicitud',
    'quote.kilos': 'Kilos',
    'quote.tons': 'Toneladas',
    'quote.containers': 'Contenedores',
    'quote.refineSearch': 'Refina tu búsqueda',
    'quote.statusSearch': 'Estatus de solicitud de cotización',
    'quote.operationType': 'Tipo operación',
    'quote.requestingExecutive': 'Ejecutivo solicitante',
    'quote.all': 'Todos',
    'quote.onlyMe': 'Solo yo',
    'quote.assignmentDate': 'Fecha de asignación',
    'quote.today': 'Hoy',
    'quote.yesterday': 'Ayer',
    'quote.lessThan5Days': 'Menos de 5 días',
    'quote.lessThan30Days': 'Menos de 30 días',
    'quote.lessThan365Days': 'Menos de 365 días',
    'quote.restore': 'Restaurar',
    'quote.done': 'Hecho',
    'quote.quotationRequest': 'Solicitud de cotizaciones',
    'quote.newRequest': 'Nueva solicitud',
    'quote.refresh': 'Actualizar',
    'quote.advancedFilters': 'Filtros avanzados',
    'quote.searchCustomer': 'Buscar cliente',
    'quote.unassigned': 'Sin asignar',
    'quote.servicesAttended': 'Servicios atendidos',
    'quote.errors.loadCatalogs': 'Error al cargar los catálogos',
    'quote.errors.loadTypesRequest': 'Error al cargar tipos de solicitud',
    'quote.errors.loadQuotation': 'Error al cargar la solicitud',
    'quote.errors.loadQuotations': 'Error al cargar las solicitudes',
    'quote.errors.updateStatus': 'Error al actualizar el estado de la cotización',
    'quote.errors.saveQuotation': 'Error al guardar la solicitud de cotización',
    'quote.errors.requestTypeNotFound': 'Error: No se pudo encontrar el tipo de solicitud seleccionado',
    'quote.errors.executivesAssingned': 'Error: Could not assigned executives',
    'quote.warnings.merchandiseName': 'Por favor ingresa el nombre de la mercancía',
    'quote.warnings.requiredFields': 'Por favor completa los campos requeridos',
    'quote.warnings.merchandisePackages': 'Por favor ingresa las unidades de la mercancía',
    'quote.warnings.merchandiseVolumenAndWeight': 'Por favor ingresa el peso y volumen total',
    'quote.warnings.IMOUN': 'Por favor ingresa IMO y UN',
    'quote.warnings.temperature': 'Por favor ingresa los grados de temperatura',
    'quote.success.updated': 'Solicitud de cotización actualizada',
    'quote.success.created': 'Solicitud de cotización creada',
    'quote.success.statusUpdated': 'Solicitud de cotización {status}',
    'quote.confirmDelete': '¿Estás seguro de eliminar esta cotización?',
    'quote.edit': 'Editar',
    'quote.noQuotations': 'No hay solicitudes de cotización',
    'quote.noResultsFilters': 'No se encontraron resultados con los filtros aplicados',
    'quote.startNewQuotation': 'Comienza creando una nueva solicitud de cotización',
    'quote.noServicesTitle': 'Sin servicios',
    'quote.noServicesMessage': 'Completa los datos de servicios.',
    'quote.noExecutivesTitle': 'Sin ejecutivos asignados',
    'quote.noExecutivesMessage': 'No has asignado ejecutivos. ¿Deseas continuar de todos modos?',
    'quote.doorToDoor': 'Puerta a Puerta',
    'quote.portToPort': 'Puerto a Puerto',
    'quote.doorToPort': 'Puerta a Puerto',
    'quote.portToDoor': 'Puerto a Puerta',
    'quote.merchandiseModal': 'Mercancía',
    'quote.dangerousClass': 'Peligrosa',
    'quote.refrigeratedClass': 'Refrigerada',
    'quote.oversizedClass': 'Sobredimensionada',
    'quote.bulkClass': 'Granel',
    'quote.generalClass': 'General',
    'quote.imo': 'IMO',
    'quote.un': 'UN',
    'quote.selectOption': 'Seleccionar',
    'quote.packagingTable.packaging': 'EMBALAJE',
    'quote.packagingTable.quantity': 'CANTIDAD',
    'quote.packagingTable.length': 'LARGO',
    'quote.packagingTable.height': 'ALTO',
    'quote.packagingTable.width': 'ANCHO',
    'quote.packagingTable.weight': 'PESO',   
    'quote.addPackagingModal': 'Agregar embalaje',  
    'quote.selectClient': 'Seleccione un cliente...',
    'quote.isBid': 'Es licitación',
    'quote.executiveAssigned': 'Ejecutivo asignado',
    'quote.creada': 'Creada',
    'quote.sent': 'Enviada',
    'quote.assigned': 'Asignada',
    'quote.quoted': 'Cotizada',
    'quote.partialquoted': 'Parcialmente cotizada',
    'quote.declined': 'Declinada',
    'quote.accepted': 'Aceptada',
    'quote.rejected': 'Rechazada',
    'quote.cancelled': 'Cancelada',
    'quote.expired': 'Expirada',
    'quote.creationDate': 'Fecha de creación',
    'quote.serviceType': 'Tipo de servicio',
    'quote.loadType': 'Tipo de carga',
    'quote.serviceaddtitle': 'No tiene servicios añadidos',
    'quote.merchaddtitle': 'No tiene mercancia añadida',
    'quote.serviceaddmessage': 'Debe agregar al menos un servicio para mandar la solicitud de cotización.',
    'quote.merchaddmessage': 'Debe agregar al menos una mercancia para mandar la solicitud de cotización.',
    'quote.accept': 'Aceptar cotización',
    'quote.cancelrequest': 'Cancelar solicitud',
    'quote.reject': 'Rechazar cotización',
    'quote.reasons': 'Motivos de cancelación',
    'quote.writereasons': 'Escriba los motivos de cancelación',
    'quote.reasonsreject': 'Motivos de rechazo',
    'quote.writereasonsreject': 'Escriba los motivos de rechazo',
    'quote.clone': 'Solicitud copiada',
    'quote.modalAutoAssign': 'Asignacion ejecutivo',
    'quote.modalAutoAssignQue': '¿Desea asignarse esta solicitud a usted mismo?',
    'quote.inputCountryNoOne': 'seleccione un registro',
    'quote.inputCountryInvalid': 'Selecciona un pais válido de la lista',
    'exec.title': 'Gestión de ejecutivos',
    'exec.newExecutive': 'Nuevo ejecutivo',
    'exec.editExecutive': 'Editar ejecutivo',
    'exec.save': 'Guardar',
    'exec.cancel': 'Cancelar',
    'exec.delete': 'Eliminar',
    'exec.actions': 'Acciones',
    'exec.search': 'Buscar por nombre, apellido, nómina o email...',
    'exec.filterAll': 'Todos',
    'exec.filterActive': 'Activos',
    'exec.filterInactive': 'Inactivos',
    'exec.nombre': 'Nombre',
    'exec.apellidoPaterno': 'Apellido paterno',
    'exec.apellidoMaterno': 'Apellido materno',
    'exec.numeroNomina': 'Número de empleado',
    'exec.fechaIngreso': 'Fecha de ingreso',
    'exec.email': 'Correo electrónico',
    'exec.departamento': 'Departamento',
    'exec.user': 'Usuario',
    'exec.activo': 'Activo',
    'exec.disponible': 'Activo',
    'exec.noDisponible': 'Inactivo',
    'exec.generalData': 'Datos del ejecutivo',
    'exec.noResults': 'No se encontraron ejecutivos',
    'exec.confirmDelete': '¿Está seguro que desea eliminar este ejecutivo?',
    'exec.successSave': 'Ejecutivo guardado',
    'exec.successDelete': 'Ejecutivo eliminado',
    'exec.errorSave': 'Error al guardar el ejecutivo',
    'exec.errorDelete': 'Error al eliminar el ejecutivo',
    'exec.errorLoad': 'Error al cargar los ejecutivos',
    'exec.nominaExists': 'El número de nómina ya existe',
    'exec.invalidEmail': 'Email inválido',
    'cust.title': 'Clientes',
    'cust.newCustomer': 'Nuevo cliente',
    'cust.editCustomer': 'Editar cliente',
    'cust.save': 'Guardar',
    'cust.cancel': 'Cancelar',
    'cust.delete': 'Eliminar',
    'cust.search': 'Buscar cliente',
    'cust.generalData': 'Datos generales',
    'cust.addresses': 'Domicilios',
    'cust.contacts': 'Contactos',
    'cust.contact': 'Contacto',
    'cust.isBranch': 'Es sucursal',
    'cust.branchName': 'Nombre de sucursal',
    'cust.type': 'Tipo persona',
    'cust.fisica': 'Física',
    'cust.moral': 'Moral',
    'cust.selectPerson': 'Seleccionar persona',
    'cust.selectCompany': 'Seleccionar empresa',
    'cust.newPerson': 'Nueva persona',
    'cust.newCompany': 'Nueva empresa',
    'cust.nationality': 'Nacionalidad',
    'cust.nacional': 'Nacional',
    'cust.Isnational': 'Nacional',
    'cust.extranjero': 'Extranjero',
    'cust.fiscalData': 'Datos Fiscales',
    'cust.businessName': 'Razón Social / IMP / EXP',
    'cust.taxId': 'RFC',
    'cust.country': 'País',
    'cust.state': 'Estado',
    'cust.personName': 'Nombre',
    'cust.birthDate': 'Fecha de nacimiento',
    'cust.companyName': 'Nombre empresa',
    'cust.errorLoadPeople': 'Error al cargar personas',
    'cust.errorLoadCompanyPeople': 'Debe seleccionar una empresa o persona',
    'cust.errorLoadcompanies': 'Error al cargar empresas',
    'cust.selectstate': 'Seleccionar estado',
    'cust.RequiredCompany': 'Selecciona la empresa',
    'cust.selectLevel': 'Selecciona nivel',
    'cust.RequiredLevel': 'Selecciona el nivel del cliente',
    "cust.clientLevel": "Nivel de cliente",
    "cust.clientLevelGold": "Oro",
    "cust.clientLevelSilver": "Plata",
    "cust.clientLevelBronze": "Bronce",
    'cust.rfc': 'RFC',
    'cust.addContact': 'Agregar contacto',
    'cust.contactType': 'Tipo',
    'cust.contactName': 'Nombre',
    'cust.contactEmail': 'Email',
    'cust.contactPhone': 'Teléfono',
    'cust.contactPosition': 'Puesto',
    'cust.addAddress': 'Agregar domicilio',
    'cust.street': 'Calle',
    'cust.city': 'Ciudad',
    'cust.postalCode': 'Código postal',
    'cust.useRegistered': 'Utilizar datos registrados',
    'cust.fiscalAddress': 'Domicilio fiscal',
    'cust.noResults': 'No se encontraron clientes',
    'cust.successSave': 'Cliente guardado',
    'cust.successDelete': 'Cliente eliminado',
    'cust.errorSave': 'Error al guardar el cliente',
    'cust.errorDelete': 'Error al eliminar el cliente',
    'cust.errorLoad': 'Error al cargar los clientes',
    'cust.errorMatrizExists': 'Esta empresa ya tiene un cliente matriz registrado.',
    'cust.enabled': 'Habilitado',
    'cust.actions': 'Acciones',
    'cust.TitleDataGeneral': 'Datos generales',
    'cust.checkActive': 'Activo',
    'cust.NaturalPerson': 'Persona física',
    'cust.TypeContact': 'Tipo de contacto',
    'cust.CompanyName': 'Razón social',
    "cust.isCorrespondent": "Corresponsal",
    'comp.errorLoadcompanyRFC': 'Debe ingresar Razón Social y RFC/TAXID',
    'comp.errorNationality': 'Debe seleccionar un país para empresas extranjeras',
    'comp.search': 'Buscar empresas',
    'comp.errorDelete': 'Error al eliminar la empresa',
    'comp.TitleEdit': 'Editar empresa',
    'comp.TitleNew': 'Nueva empresa',
    'comp.SelectCountry': 'Seleccione país',
    'comp.CompanyName': 'Razón social',
    'comp.state': 'Estado',
    'comp.Nacionality': 'Nacionalidad',
    'comp.Country': 'País',
    'comp.status': 'Estatus',
    'comp.Save': 'Guardar',
    'comp.Cancel': 'Cancelar',
    'comp.LoadCompanies': 'Cargando empresas...',
    'comp.Isnational': 'Es nacional',
    'comp.okupdate': 'Empresa actualizada correctamente',
    'comp.oksave': 'Empresa creada correctamente',
    'comp.DeleteSucess': 'Empresa eliminada',
    'comp.CompanynameRequired': 'Capture la razón social',
    'comp.RFCTAXIDRequired': 'Capture el RFC/TaxID',
    'comp.stateRequired': 'Capture el estado',
    'supp.title': 'Proveedores',
    'supp.newSupplier': 'Nuevo proveedor',
    'supp.editSupplier': 'Editar proveedor',
    'supp.search' : 'Buscar proveedor, taxid',
    'supp.selectCompany': 'Seleccionar compañia',
    'supp.newCompany': 'Nueva empresa',
    'supp.IsNational': 'Nacional',
    'supp.IsPersonFisica': 'Persona física',
    'supp.selectSector': 'Seleccionar sector',
    'supp.generalData': 'Datos generales',
    'supp.noResults': 'No se encontraron proveedores',
    'supp.errorSave': 'Error al guardar el proveedor',
    'supp.errorDelete': 'Error al eliminar el proveedor',
    'supp.save': 'Guardar',
    'supp.cancel': 'Cancelar',
    'supp.contacts': 'Contactos',
    'supp.contact': 'Contacto',
    'supp.addContact': 'Agregar contacto',
    'supp.TypeContact': 'Tipo de contacto',
    'supp.contactName': 'Nombre',
    'supp.contactEmail': 'Email',
    'supp.contactPhone': 'Teléfono',
    'supp.activo': 'Activo',
    'supp.addresses': 'Domicilios',
    'supp.addAddress': 'Agregar domicilio',
    'supp.address': 'Domicilio',
    'supp.street': 'Calle',
    'supp.city': 'Ciudad',
    'supp.state': 'Estado',
    'supp.postalCode': 'Código postal',
    'nav.catalogs': 'Catálogos',
    'nav.catalogs.imo': 'IMO',
    'nav.catalogs.incoterms': 'Incoterms',
    'nav.catalogs.services': 'Servicios',
    'nav.catalogs.status': 'Estatus',
    'nav.catalogs.requestTypes': 'Tipos de solicitud',
    'nav.catalogs.requestType': 'Tipo de solicitud',
    'nav.catalogs.countries': 'Países',
    'nav.catalogs.country': 'País',
    'nav.catalogs.sectorOfBusiness': 'Sector de negocios',
    'nav.catalogs.companies': 'Empresas',
    'nav.catalogs.users': 'Usuarios',
    'nav.catalogs.clauses': 'Cláusulas',
    'catalog.title': 'Catálogo de {name}',
    'catalog.new': 'Nuevo {name}',
    'catalog.edit': 'Editar {name}',
    'catalog.save': 'Guardar',
    'catalog.saving': 'Guardando...',
    'catalog.cancel': 'Cancelar',
    'catalog.continue': 'Continuar',
    'catalog.delete': 'Eliminar',
    'catalog.search': 'Buscar...',
    'catalog.actions': 'Acciones',
    'catalog.noResults': 'No se encontraron resultados',
    'catalog.confirmDelete': '¿Está seguro que desea eliminar este registro?',
    'catalog.successSave': 'Registro guardado',
    'catalog.successDelete': 'Registro eliminado',
    'catalog.errorSave': 'Error al guardar el registro',
    'catalog.errorDelete': 'Error al eliminar el registro',
    'catalog.errorLoad': 'Error al cargar los datos',
    'catalog.errorUpdate': 'Error al actualizar los datos',
    'catalog.imo.code': 'Código IMO',
    'catalog.imo.description': 'Descripción',
    'catalog.incoterm.code': 'Incoterm',
    'catalog.service': 'Servicio',
    'catalog.service.name': 'Nombre del servicio',
    'catalog.service.category': 'Categoría',
    'catalog.service.categoryMain': 'Principal',
    'catalog.service.categoryAccessory': 'Accesorio',
    'catalog.service.email': 'Email',
    'catalog.requestType.name': 'Tipo de solicitud',
    'catalog.status.category': 'Categoría',
    'catalog.status.subcategory': 'Subcategoría',
    'catalog.status.code': 'Código',
    'catalog.status.name': 'Nombre',
    'catalog.status.description': 'Descripción',
    'catalog.status.active': 'Activo',
    'catalog.status.inactive': 'Inactivo',
    'catalog.filterAll': 'Todos',
    'catalog.filterActive': 'Activos',
    'catalog.filterInactive': 'Inactivos',
    'catalog.country.code': 'Código del país',
    'catalog.country.name': 'Nombre del país',
    'catalog.sectorOfBusiness.name': 'Nombre del sector',
    'catalog.sectorOfBusiness.description': 'Descripción',
    'catalog.requiredFields': 'Por favor complete todos los campos requeridos',
    'catalog.optional': '(Opcional)',
    'catalog.exists': 'Este {name} ya existe.',
    'catalog.clause.tags': 'Tags',
    'catalog.clause.title': 'Título',
    'catalog.clause.es': 'Cláusula',
    'catalog.clause.en': 'Cláusula (inglés)',
    'ctrlpricing.title': 'Control de pricing',
    'ctrlpricing.refresh': 'Actualizar',
    'ctrlpricing.filtro': 'Filtros',
    'ctrlpricing.actions': 'Acciones',
    'ctrlpricing.search': 'Buscar solicitud',
    'ctrlpricing.edit': 'Editar',
    'ctrlpricing.delete': 'Eliminar',
    'ctrlpricing.addcontrol': 'Agregar número de control',
    'ctrlpricing.norequests': 'No hay solicitudes disponibles',
    'ctrlpricing.noresults': 'No se encontraron resultados con los filtros aplicados',
    'ctrlpricing.noresultsstatus': 'No hay solicitudes con estado mayor o igual a 3',
    'ctrlpricing.servicesattended': 'Servicios atendidos',
    'ctrlpricing.unassigned': 'Sin asignar',
    'ctrlpricing.editcontrolnumber': 'Editar número de control',
    'ctrlpricing.newcontrolnumber': 'Nuevo número de control',
    'ctrlpricing.save': 'Guardar',
    'ctrlpricing.export': 'Exportar',
    'ctrlpricing.duplicate': 'Duplicar',
    'ctrlpricing.historical': 'Historial',
    'ctrlpricing.priority': 'Prioridad',
    'ctrlpricing.bidding': 'Licitación',
    'ctrlpricing.decline': 'Declinar',
    'ctrlpricing.quoted': 'Cotizada',
    'ctrlpricing.supplierassignment': 'Asignación de proveedores',
    'ctrlpricing.supplier': 'Proveedor',
    'ctrlpricing.suppliername': 'Nombre del proveedor',
    'ctrlpricing.addsupplier': 'Agregar proveedor',
    'ctrlpricing.status': 'Estatus',
    'ctrlpricing.network': 'Red / Alianza',
    'ctrlpricing.complexity': 'Complejidad',
    'ctrlpricing.currency': 'Moneda',
    'ctrlpricing.unitprofit': 'Profit unitario',
    'ctrlpricing.volume': 'Volumen',
    'ctrlpricing.generalprofit': 'Profit general',
    'ctrlpricing.comments': 'Comentarios',
    'ctrlpricing.services': 'Servicios',
    'ctrlpricing.serviceincluded': 'Servicio incluido',
    'ctrlpricing.alreadyused': 'Ya usado en otro control',
    'ctrlpricing.includeservice': 'Incluir servicio',
    'ctrlpricing.service': 'Servicio',
    'ctrlpricing.operation': 'Operación',
    'ctrlpricing.expecteddeparture': 'Salida esperada',
    'ctrlpricing.origin': 'Origen',
    'ctrlpricing.destination': 'Destino',
    'ctrlpricing.cpd': 'Código postal de destino',
    'ctrlpricing.cpo': 'Código postal de origen',
    'ctrlpricing.shippingtype': 'Tipo de envío',
    'ctrlpricing.associatedServices': 'Servicios asociados',
    'ctrlpricing.noassociatedservices': 'Sin servicios asociados',
    'ctrlpricing.nocomments': 'Sin comentarios',
    'ctrlpricing.programFrequency': 'Programar frecuencia',
    'ctrlpricing.frequency': 'Frecuencia',
    'ctrlpricing.quantity': 'Cantidad',
    'ctrlpricing.unit': 'Medida',
    'ctrlpricing.commodity': 'MERCANCÍA',
    'ctrlpricing.dangerous': 'PELIGROSA',
    'ctrlpricing.classification': 'CLASIFICACIÓN',
    'ctrlpricing.stackable': 'ESTIBABLE',
    'ctrlpricing.totalVolume': 'VOL. TOTAL',
    'ctrlpricing.totalWeight': 'PESO TOTAL',
    'ctrlpricing.refineSearch': 'Refina tu búsqueda',
    'ctrlpricing.requestdate': 'Fecha de solicitud',
    'ctrlpricing.today': 'Hoy',
    'ctrlpricing.yesterday': 'Ayer',
    'ctrlpricing.less5days': 'Menos de 5 días',
    'ctrlpricing.less30days': 'Menos de 30 días',
    'ctrlpricing.less365days': 'Menos de 365 días',
    'ctrlpricing.assignedexecutive': 'Ejecutivo asignado',
    'ctrlpricing.all': 'Todos',
    'ctrlpricing.onlyme': 'Solo yo',
    'ctrlpricing.select': 'Seleccionar',
    'ctrlpricing.selectexecutive': 'Seleccionar ejecutivo...',
    'ctrlpricing.selectprov': 'Debe seleccionar un proveedor',
    'ctrlpricing.documents': 'Documentos',
    'ctrlpricing.portO': 'Puerto Origen',
    'ctrlpricing.portD': 'Puerto Destino',
    'ctrlpricing.airportO': 'Aeropuerto Origen',
    'ctrlpricing.airportD': 'Aeropuerto Destino',
    'ctrlpricing.provalreadyadded': 'Proveedor ya agregado',
    'ctrlpricing.selectnetwork': 'Debe seleccionar una red/alianza',
    'ctrlpricing.capturevolume': 'Debe capturar el volumen para calcular el profit general',
    'ctrlpricing.customercorrespondent': 'Cliente del Corresponsal',
    'ctrlpricing.customerlead': 'Cliente lead',
    'ctrlpricing.affair': 'Asunto',
    'ctrlpricing.cityo': 'Ciudad de origen',
    'ctrlpricing.cityd': 'Ciudad de destino',
    'ctrlpricing.generateSaleRate': 'Tarifa final',
    'tracking.title': 'Monitor de Rastreo',
    'tracking.subtitle': 'Rastrea tus contenedores en tiempo real',
    'user.title': 'Usuarios',
    'user.newUser': 'Nuevo usuario',
    'user.editUser': 'Editar usuario',
    'user.save': 'Guardar',
    'user.cancel': 'Cancelar',
    'user.delete': 'Eliminar',
    'user.actions': 'Acciones',
    'user.search': 'Buscar por nombre, apellido o email...',
    'user.filterAll': 'Todos',
    'user.filterAdmins': 'Administradores',
    'user.filterActive': 'Activos',
    'user.filterInactive': 'Inactivos',
    'user.name': 'Nombre',
    'user.fullName': 'Nombre completo',
    'user.email': 'Correo Electrónico',
    'user.departamento': 'Departamento',
    'user.roles': 'Roles',
    'user.user': 'Usuario',
    'user.activo': 'Activo',
    'user.errorLoad': 'Error al cargar los usuarios',
    'user.successSave': 'Usuario guardado',
    'user.errorSave': 'Error al guardar el usuario',
    'user.successDelete': 'Usuario eliminado',
    'user.errorDelete': 'Error al eliminar el usuario',
    'user.noResults': 'No se encontraron usuarios',
    'user.password': 'Contraseña',
    'user.created': 'Creado',
    'user.admin': 'Administrador',
    'modal.message': '¿Desea continuar con la eliminación?',
    'modal.title': 'Está a punto de eliminar este {name}.',
    'filter.restore': 'Restaurar',
    'filter.done': 'Hecho',
    'dash.title': 'Panel',
    'dash.subtitle': 'Monitoreo de rendimiento de clientes y estados de cotización.',
    'dash.CustomerCategorization':'Categorización de Clientes',
    'dash.CustomerCategorization.total': 'Total {count} clientes',
    'dash.quotationrequest': 'Solicitar cotización',
    'dash.statementofContributions': 'Estado de Cotizaciones',
    'dash.quotes.urgent': 'Cotizaciones Urgentes',
    'dash.quotes.recent': 'Cotizaciones Recientes',
    'dash.quotes.records': 'Mostrando {record} de {records} registros',
    'dash.table.col.client': 'Cliente',
    'dash.table.col.type': 'Tipo',
    'dash.table.col.expiration': 'Vencimiento',
    'dash.table.col.status':'Estado',
    'dash.table.col.actions': 'Acciones',
    'dash.table.viewDetail': 'Detalle',
    'dash.performanceperchannel.title':'Rendimiento por canal',
    'dash.performanceperchannel.subtitle':'Solicitudes Aceptadas',
	  'dash.performanceperchannel.adress':'Dirección',
    'dig.title': 'Digitalización',
    'dig.refineSearch': 'Refina tu búsqueda',
    'dig.reference': 'Referencia',
    'dig.section': 'Sección',
    'dig.documentType': 'Tipo de documento',
    'dig.all': 'Todos',
    'dig.restore': 'Restaurar',
    'dig.apply': 'Aplicar',
    'dig.searchDocument': "Buscar por documento, referencia de cotización o cliente...",
    'dig.recentFiles': 'Archivos cargados recientemente...',
    'dig.selectAll': 'Seleccionar todo',
    'dig.unselectAll': 'Deseleccionar todo',
    'dig.selected': 'seleccionados',
    'dig.download': 'Descargar',
    'dig.downloadfiles': 'Descargar archivos',
    'dig.downloadfile': 'Descargar archivo',
    'dig.delete': 'Eliminar',
    'dig.noResults': 'No se encontraron resultados',
    'dig.uploadDocuments': 'Cargar documentos',
    'dig.dragFiles': 'Arrastra archivos aquí',
    'dig.clickToSelect': 'o haz clic para seleccionar desde tu equipo',
    'dig.fileType': 'Tipo documento',
    'dig.upload': 'Subir archivo',
    'dig.uploading': 'Subiendo archivos...',
    'dig.cancel': 'Cancelar',
    'dig.refresh': 'Actualizar',
    'dig.filters': 'Filtros',
    'dig.uploadFiles': 'Cargar archivos',
    'dig.deleteDocument': 'Eliminar documento',
    'dig.deleteDocumentConfirm': '¿Deseas eliminar "{{name}}"?',
    'dig.deleteSuccess': 'Documento eliminado correctamente',
    'dig.deleteError': 'Error al eliminar documento',
    'dig.deleteDocuments': 'Eliminar documentos',
    'dig.deleteDocumentsConfirm': '¿Eliminar {{count}} documentos seleccionados?',
    'dig.deleteDocumentsSuccess': 'Documentos eliminados correctamente',
    'dig.referenceRequired': 'Debe ingresar una referencia',
    'dig.downloadError': 'Error al descargar archivo',
    'dig.downloadFailed': 'No se pudo descargar el archivo',
    'dig.catalogError': 'No se encontró información',
    'dig.uploadValidation': 'Debes llenar los campos referencia, tipo doc. y sección',
    'dig.uploadError': 'Error al subir archivos',
    'dig.uploadCanceled': 'Carga cancelada',
    'dig.uploadingFiles': 'Subiendo {{count}} archivo(s)...',
    'dig.uploadFilesCount': 'Subir {{count}} archivo(s)',
    'dig.uploadFile': 'Subir archivo',
    'dig.selectedFiles': 'Archivos seleccionados',
    'dig.searchReference': 'Referencia',
    'dig.fileDownloaded': 'Archivo {{name}} descargado',
    'dig.zipDownloaded': '{{count}} archivos descargados en ZIP',
    'dig.downloadFilesError': 'Error al descargar archivos',
    'dig.fileUploaded': 'Registro del archivo {{name}}',
    'dig.fileUploadError': 'Error al subir {{name}}',
    'dig.documents': 'Documentos',
    'dig.ErrorGetDocumentsByReference': 'Error al obtener los documentos por la referencia',
    "dig.noReference": "La solicitud no tiene referencia",
    "dig.noDocuments": "No hay documentos para descargar",
    "dig.invalidDocument": "Documento inválido",
    "dig.cannotDelete": "No se puede eliminar el documento",
    "dig.documentHasAcceptedRate": "No puedes eliminar este documento porque tiene una tarifa aceptada por el cliente",
    "dig.documentHasAcceptedRateSingle": "No se puede eliminar el documento porque ha sido aceptado por el cliente",
    "dig.documentHasAcceptedRateMultiple": "No se pueden eliminar {{count}} documentos porque han sido aceptados por el cliente",
    "dig.OKmodal": "Aceptar",
    "tvf.title": "Tarifa de venta final",
    "tvf.subtitle": "Control pricing",
    "tvf.subtitleGeneral": "General",
    "tvf.Draft": "Borrador",
    "tvf.LanguageFormat": "Formato idioma",
    "tvf.LanguageSpanish": "Español",
    "tvf.LanguageEnglish": "Inglés",
    "tvf.Preview": "Vista previa",
    "tvf.ViewRate": "Ver Tarifa",
    "tvf.ExecutiveInCharge": "Ejecutivo a cargo",
    "tvf.QuoteRequestRef": "Referencia solicitud cotización",
    "tvf.Quota": "# Cuota",
    "tvf.Version": "Versión # ",
    "tvf.OfferValidity": "Validez de oferta",    
    "tvf.Services": "Servicios",
    "tvf.Export": "Exportación",
    "tvf.Import": "Importación",
    "tvf.DoorToPort": "Puerta a Puerto",
    "tvf.LogisticRoute": "Ruta logística",
    "tvf.PortOfOrigin": "Puerto origen",
    "tvf.PortOfDestination": "Puerto destino",
    "tvf.CargoSummary": "Resumen de carga",
    "tvf.Goods": "Mercancía",
    "tvf.AssociatedServices": "Servicios asociados",
    "tvf.Concepts": "Conceptos",
    "tvf.AdditionalNotesComments": "Notas adicionales y comentarios",
    "tvf.TermsConditions": "Términos y condiciones",
    "tvf.SubtotalAmount": "Importe Subtotal",
    "tvf.EstimatedTaxVAT": "Impuesto Estimado (IVA)",
    "tvf.TotalAmount": "Importe Total",
    "tvf.SearchOrAddTerms": "Buscar o agregar términos...",
    "tvf.MaritimeConcepts": "Conceptos marítimos",
    "tvf.AirConcepts": "Conceptos aéreos",
    "tvf.AirOperationalConcepts": "Conceptos operativos aéreos",
    "tvf.LandConcepts": "Conceptos terrestres",
    "tvf.currency": "Divisa",
    "tvf.currencyConversion": "Conversión divisa",
    "tvf.ExchangeRate": "Tipo cambio",
    "tvf.Generate": "Generar",
    "tvf.AddNewConcept": "Agregar concepto",
    "tvf.Maritime": "Marítimo",
    "tvf.Air": "Aéreo",
    "tvf.Land": "Terrestre",
    "tvf.BreakdownByCharges": "Desglose por cargos",
    "tvf.Charge": "Cargo",
    "tvf.Subtotal": "Subtotal",
    "tvf.VAT": "IVA",
    "tvf.Total": "Total",
    "tvf.Concept": "Concepto",
    "tvf.Base": "Base",
    "tvf.Container": "Contenedor",
    "tvf.Unit": "Unidad",
    "tvf.Actions": "Acciones",
    "tvf.Airline": "Aerolínea",
    "tvf.Route": "Ruta",
    "tvf.Transit": "Tránsito",
    "tvf.RateKG": "Tarifa/KG",
    "tvf.FCS": "FCS",
    "tvf.SSC": "SSC",
    "tvf.MCC": "MCC",
    "tvf.CW": "CW",
    "tvf.ConsultingServicesConcepts": "Conceptos de accesorios",
    "tvf.noQuote": "Sin folio",
    "tvf.Advisory": "Accesorial",
    "tvf.GenerateOK": "Tarifa de venta generada correctamente, numero cuota: ",
    "tvf.GenerateError": "Error al generar la tarifa de venta",
    "tvf.UpdateOK": "Tarifa de venta actualizada",
    "tvf.UpdateStatusError": "Ocurrio un error al actualizar status tarifa de venta",
    "tvf.UpdateError": "Ocurrio un error al actualizar la tarifa de venta",
    "tvf.UpdateStatusControlOK": "Estatus del control actualizado correctamente",
    "tvf.UpdateStatusControlError": "Ocurrio un error al actualizar el estatus del control",
    "tvf.SinConceptos": "Sin conceptos",
    "tvf.Origen": "Origen",
    "tvf.Destino": "Destino",
    "tvf.TermsPlaceholder" : "Escribe o pega los términos y condiciones...",
    "tvf.Elegir": "Elegir",
    "tvf.ElegirContenedor": "Elegir contenedor...",
    "tvf.TotalMustBeGreaterThanZero": "El total de los conceptos debe ser mayor a cero",
    "tvf.GenerateTitle": "Generar nueva versión",
    "tvf.GenerateConfirmMessage": "Se creará una nueva versión #{version} de la cotización. ¿Deseas continuar?",
    "tvf.NoContacts":"Sin contactos",
    "tvf.GenerateCancel":"Cancelar",
    "tvf.Contact":"Contacto",
    "tvf.NoName": "Sin nombre",
    "tvf.NoEmail": "Sin correo",
    "tvf.NoPhone": "Sin teléfono",
    "tvf.NoCharge":"SIN CARGO",
    "tvf.ContactRequired": "El contacto es requerido",
    "tvf.CurrencyRequired": "La moneda es requerida",
    "tvf.CurrencyToRequired": "La moneda de conversión es requerida",
    "tvf.ExchangeRateRequired": "El tipo de cambio es requerido",
    "tvf.ValidFromRequired": "La fecha validez inicial es requerida",
    "tvf.ValidUntilRequired": "La fecha validez final es requerida",
    "tvf.RequiredFields": "Campos requeridos",
    "tvf.FieldRequired": "requerido",
    "tvf.AirOperational": "Aéreo Operativo",
    "tvf.termsValueRequired": "Requiere terminos y condiciones",
    "tvf.ValidUntilMustBeGreater": "La fecha final no puede ser menor a la fecha inicial",
    "tvf.WarningTitle": "Confirmación de cambio de estatus",
    "tvf.ChangeStatusToDraftMessagept1": "La tarifa se encuenta en estatus ",
    "tvf.ChangeStatusToDraftMessagept2": "Se actualizará a Borrador. ¿Deseas continuar?",
    "tvf.Confirm": "Confirmar",
    "tvf.Cancel": "Cancelar",
    "tvf.UpdateToDraft": "Actualizar a borrador",
    "tvf.PdfUploadOK": "PDF generado y subido correctamente",
    "tvf.PdfUploadError": "No se pudo subir el documento",
    "tvf.ConceptSubtotalRequired": "Cada concepto debe incluir un nombre y un importe mayor a 0.",
    "tvf.PdfUploadWarning": "La cotización se generó, pero el PDF no se pudo subir.",
    "tvf.generatingPdf": "Generando PDF...",
    "tvf.pleaseWait": "Espere un momento...",
    "tvf.Noaddress": "Sin dirección",
    "tvf.enterAddress": "ingresa la dirección",
    "tvf.Name": "Nombre",
    "tvf.Email": "Correo electrónico",
    "tvf.Phone": "Teléfono",
    "tvf.NameRequired": "El nombre contacto es obligatorio",
    "tvf.EmailRequired": "El correo del contacto es obligatorio",
    "tvf.PhoneRequired": "El teléfono  del contacto es obligatorio",
    "tvf.SaveError": "Error al guardar",
    "tvf.GeneralError": "General error",
    "tvf.SavedAt": "Guardado ",
    "tvf.ConceptUnValid": "La fila {row} contiene datos numéricos incorrectos. Revise importe, unidades o cargos.",
    "tvf.WithoutFolio": "Sinfolio",
    "tvf.Duplicate": "Duplicar",
    "tvf.Delete": "Eliminar",
    "score.scoreQuotations" : "Score Cotizaciones",
    "score.scoreQuotationsResume" : "Seguimiento en tiempo real del estado y desempeño del equipo de Pricing en el proceso de cotizaciones.",
    "score.print" : "Imprimir",
    "score.totalQuotations" : "Cotizaciones acumuladas",
    "score.quotations" : "Cotizaciones ",
    "score.quotationsPendients" : "Pendientes",
    "score.quotationsAccepted" : "Aceptadas",
    "score.totalQuotationsResume" : "Actividad acumulada en la plataforma durante el año actual ",
    "score.quotationsAcceptedMonth": "Cotizaciones aceptadas ",
    "score.individualMetrics": "Score Individual",
    "score.accumulated": "acumulado",
    "report.title": "Reportes",
    "report.subtitle": "Seleccione un reporte para consultar",
    "report.seartoogle":"Buscar reportes por clave o nombre",
    "report.header1":"Clave",
    "report.header2":"Categoría",
    "report.header3":"Nombre",
    "report.header4":"Descripción",
    "report.header5":"Creator",
    "report.header6":"Registro",
    "report.titleparameter":"Parametros configurados del reporte",
    "report.subtitleparameter":"Refinar el alcance de los datos para el resumen.",
    "report.button": "Generar resultados",
    "report.filter": "Mas filtros", 
    "report.show": "Mostrar", 
    "report.show2": "reportes",
    "report.show3": "registros",
    "report.show4": "de",
    "report.titleresult":"Resultados de Consulta",
    "report.generatedby":"Generado por",
    "report.generationdate":"Fecha de generación",
    "report.mesage1":"Debe capturar al menos un parámetro para generar el reporte.",
    "report.mesage2":"El reporte no generó resultados con los parámetros proporcionados.",
    "operations.title": "Operaciones",
    "operations.search": "Buscar por referencia, cliente o control de pricing...",
    "operations.newOperation": "Nueva operación",
    "operations.editOperation": "Editar operación",
    "operations.generalData": "Datos generales",
    "operations.services": "Servicios",
    "operations.merchandise": "Mercancía",
    "operations.reference": "Referencia",
    "operations.customer": "Cliente",
    "operations.selectCustomer": "Seleccionar un cliente...",
    "operations.controls": "Controles",
    "operations.selectControl": "Seleccionar un control...",
    "operations.addControl": "Agregar control",
    "operations.selectControlWarning": "Por favor, selecciona un control para agregar",
    "operations.selectService": "Seleccionar un servicio...",
    "operations.addService": "Agregar servicio",
    "operations.selectServiceWarning": "por favor, selecciona un servicio para agregar",
    "operations.observations": "Observaciones",
    "operations.listaparafacturar": "Lista para facturar",
    "operations.countryCharge": "Pais de carga",
    "operations.arrivalPlant": "Llegada a planta",
    "operations.portDischarge": "Puerto de descarga",
    "operations.airportDischarge": "Aeropuerto de descarga",
    "operations.tieneControl": "¿Tiene número de control?",
    "operations.shipment": "Envio",
    "operations.mode": "Modalidad",
    "operations.operationtype": "Tipo operación",
    "operations.incoterm": "Inconterm",
    "operations.transport": "Transporte",
    "operations.carrier": "Transportista",
    "operations.unitType": "Tipo de unidad",
    "operations.bookingNumber": "Número de reserva",
    "operations.bookingDate": "Fecha de reserva",
    "operations.unitName": "Nombre de la unidad",
    "operations.plates": "Placas",
    "operations.routeType": "Tipo ruta",
    "operations.plantAppointment": "Cita en planta",
    "operations.movementType": "Tipo de movimiento",
    "operations.typeGuide": "Tipo | Guía",
    "operations.origin": "Origen",
    "operations.destination": "Destino",
    "operations.collectionLocation": "Lugar de recolección",
    "operations.plantExit": "Salida de planta",
  },
  en: {
    'app.title': 'Singularity',
    'app.loading': "Loading",
    'nav.dashboard': 'Dashboard',
    'nav.quotations': 'Quotation request',
    'nav.controlsPricing': 'Pricing controls',
    'nav.trackingMonitor': 'Tracking monitor',
    'nav.executives': 'Executives',
    'nav.shipments': 'Shipments',
    'nav.customers': 'Customers',
    'nav.companies': 'Companies',
    'nav.suppliers': 'Suppliers',
    'nav.operations': 'Operations',
    'nav.documents': 'Documents',
    'nav.analytics': 'Analytics',
    'nav.settings': 'Settings',
    'nav.reports': 'Reports',
    'nav.digitization': 'Digitization',
    'auth.login': 'Sign In',
    'auth.signup': 'Sign Up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm password',
    'auth.loginButton': 'Sign In',
    'auth.signupButton': 'Create account',
    'auth.noAccount': "Don't have an account?",
    'auth.haveAccount': 'Already have an account?',
    'auth.forgotPassword': 'Forgot your password?',
    'auth.welcome':"Welcome back",
    'auth.createAccount':"Create your account",
    'header.search': 'Search request',
    'header.logout': 'Sign Out',
    'header.profile': 'Profile',
    'quote.title': 'New quotation request',
    'quote.save': 'Save',
    'quote.sendForQuote': 'Send for quote ',
    'quote.generalData': 'General data',
    'quote.client': 'Client',
    'quote.prospect': 'Prospect',
    'quote.isProspect': 'Is prospect',
    'quote.isPriority': 'Is priority',
    'quote.isQuote': 'Is tender',
    'quote.requestType': 'Request type',
    'quote.orderBy': 'Order by',
    'quote.orderDesc': 'Descendant',
    'quote.applicant': 'Applicant',
    'quote.created': 'Created',
    'quote.responseDeadline': 'Response deadline',
    'quote.services': 'Services',
    'quote.service': 'Service',
    'quote.operation': 'Operation',
    'quote.incoterm': 'Incoterm',
    'quote.expectedDeparture': 'Expected departure',
    'quote.origin': 'Origin',
    'quote.originZip' : 'Origin zip code',
    'quote.originPort' : 'Origin port',
    'quote.originAirport' : 'Origin airport',
    'quote.destination': 'Destination',
    'quote.destinationZip': 'Destination zip code',
    'quote.destinationPort' : 'Destination port',
    'quote.destinationAirport' : 'Destination airport',
    'quote.shippingType': 'Shipping type',
    'quote.associatedServices': 'Associated services',
    'quote.custody': 'Custody',
    'quote.insurance': 'Insurance',
    'quote.inspection': 'Inspection',
    'quote.customsClearance': 'Customs clearance',
    'quote.warehouse': 'Warehouse',
    'quote.parcelService': 'Parcel Service',
    'quote.PreInspectionOrigin': 'Preinspection at origin',
    'quote.comments': 'Comments',
    'quote.frequency': 'Frequency',
    'quote.quantity': 'Quantity',
    'quote.unit': 'Unit',
    'quote.frequencyPeriod': 'Frequency',
    'quote.merchandise': 'Merchandise',
    'quote.search': 'Search by reference, customer or type request',
    'quote.actions': 'Actions',
    'quote.reference': 'Reference',
    'quote.customer': 'Customer',
    'quote.selectCustomer': 'Select a customer...',
    'quote.selectType': 'Select a type...',
    'quote.customerCategory': 'Customer category',
    'quote.requestDate': 'Request date',
    'quote.cancel': 'Cancel',
    'quote.select': 'Select...',
    'quote.export': 'Exportación',
    'quote.import': 'Importación',
    'quote.national': 'Nacional',
    'quote.localUSA': 'Local USA',
    'quote.Triangulacion': 'Triangulación',
    'quote.selectCountry': 'Select country...',
    'quote.maneuver': 'Maneuver',
    'quote.programFrequency': 'Program frequency',
    'quote.weekly': 'Semanal',
    'quote.monthly': 'Mensual',
    'quote.yearly': 'Anual',
    'quote.dangerous': 'Dangerous',
    'quote.classification': 'Classification',
    'quote.stackable': 'Stackable',
    'quote.totalVolume': 'Total volume',
    'quote.totalWeight': 'Total weight',
    'quote.volumetricWeightTotal': 'Volumetric weight total',
    'quote.yes': 'Yes',
    'quote.no': 'No',
    'quote.refrigerated': 'Refrigerated',
    'quote.general': 'General',
    'quote.copy': 'Copy',
    'quote.delete': 'Delete',
    'quote.view': 'View',
    'quote.addMerchandise': 'Add merchandise',
    'quote.addService': 'Add Service',
    'quote.executiveAssignment': 'Executive assignment',
    'quote.executive': 'Executive',
    'quote.addExecutive': 'Add executive',
    'quote.isStackable': 'Is stackable',
    'quote.merchandiseDescription': 'Merchandise description',
    'quote.merchandiseClassification': 'Merchandise classification',
    'quote.oversized': 'Oversized',
    'quote.temperature': 'Temperature',
    'quote.bulk': 'Bulk',
    'quote.addPackaging': 'Add packaging',
    'quote.packaging': 'Packaging',
    'quote.length': 'Length',
    'quote.height': 'Height',
    'quote.width': 'Width',
    'quote.weight': 'Weight',
    'quote.packagingType': 'Packaging type',
    'quote.box': 'Caja',
    'quote.bundle': 'Bundle',
    'quote.pallet': 'Pallet',
    'quote.container': 'Container',
    'quote.selectcontainer': 'Select container',
    'quote.allContainersAdded': 'No containers available',
    'quote.unitVolume': 'Unit of volume',
    'quote.unitWeight': 'Unit of weight',
    'quote.drum': 'Tambor',
    'quote.sack': 'Sack',
    'quote.add': 'Add',
    'quote.continue': 'Continue',
    'quote.selectExecutive': 'Select executive',
    'quote.allExecutivesAdded': 'All available executives have been added',
    'quote.saving': 'Saving...',
    'quote.viewTitle': 'View quotation',
    'quote.editTitle': 'Edit request',
    'quote.kilos': 'Kilos',
    'quote.tons': 'Toneladas',
    'quote.containers': 'Containers',
    'quote.refineSearch': 'Refine your search',
    'quote.statusSearch': 'Quotation request status',
    'quote.operationType': 'Operation type',
    'quote.requestingExecutive': 'Requesting executive',
    'quote.all': 'All',
    'quote.onlyMe': 'Only me',
    'quote.assignmentDate': 'Assignment date',
    'quote.today': 'Today',
    'quote.yesterday': 'Yesterday',
    'quote.lessThan5Days': 'Less than 5 days',
    'quote.lessThan30Days': 'Less than 30 days',
    'quote.lessThan365Days': 'Less than 365 days',
    'quote.restore': 'Restore',
    'quote.done': 'Done',
    'quote.quotationRequest': 'Quotation request',
    'quote.newRequest': 'New request',
    'quote.refresh': 'Refresh',
    'quote.advancedFilters': 'Advanced filters',
    'quote.searchCustomer': 'Search customer',
    'quote.unassigned': 'Unassigned',
    'quote.servicesAttended': 'Services attended',
    'quote.errors.loadCatalogs': 'Error loading catalogs',
    'quote.errors.loadTypesRequest': 'Error loading requests types',
    'quote.errors.loadQuotation': 'Error loading quotation request',
    'quote.errors.loadQuotations': 'Error loading quotations request',
    'quote.errors.updateStatus': 'Error updating quotation status',
    'quote.errors.saveQuotation': 'Error saving quotation request',
    'quote.errors.requestTypeNotFound': 'Error: Could not find the selected request type',
    'quote.errors.executivesAssingned': 'Error al asignar ejecutivos a la cotización',
    'quote.warnings.merchandiseName': 'Please enter the merchandise name',
    'quote.warnings.requiredFields': 'Please complete the required fields',
    'quote.warnings.merchandisePackages': 'Please add the packages of the merchandise',
    'quote.warnings.merchandiseVolumenAndWeight': 'Please add the weight and volume',
    'quote.warnings.IMOUN': 'Please add IMO and UN',
    'quote.warnings.temperature': 'Please add the temperature grades',
    'quote.success.updated': 'Quotation request updated',
    'quote.success.created': 'Quotation request created',
    'quote.success.statusUpdated': 'Quotation request {status}',
    'quote.confirmDelete': 'Are you sure you want to delete this quotation?',
    'quote.edit': 'Edit',
    'quote.noQuotations': 'No quotation requests',
    'quote.noResultsFilters': 'No results found with the applied filters',
    'quote.startNewQuotation': 'Start by creating a new quotation request',
    'quote.noServicesTitle': 'No services',
    'quote.noServicesMessage': 'You have not added any services. Do you want to continue anyway?',
    'quote.noExecutivesTitle': 'No executives assigned',
    'quote.noExecutivesMessage': 'You have not assigned any executives. Do you want to continue anyway?',
    'quote.doorToDoor': 'Puerta a Puerta',
    'quote.portToPort': 'Puerto a Puerto',
    'quote.doorToPort': 'Puerta a Puerto',
    'quote.portToDoor': 'Puerto a Puerta',
    'quote.merchandiseModal': 'Merchandise',
    'quote.dangerousClass': 'Dangerous',
    'quote.refrigeratedClass': 'Refrigerated',
    'quote.oversizedClass': 'Oversized',
    'quote.bulkClass': 'Bulk',
    'quote.generalClass': 'General',
    'quote.imo': 'IMO',
    'quote.un': 'UN',
    'quote.selectOption': 'Select',
    'quote.packagingTable.packaging': 'PACKAGING',
    'quote.packagingTable.quantity': 'QUANTITY',
    'quote.packagingTable.length': 'LENGTH',
    'quote.packagingTable.height': 'HEIGHT',
    'quote.packagingTable.width': 'WIDTH',
    'quote.packagingTable.weight': 'WEIGHT',
    'quote.addPackagingModal': 'Add packaging',
    'quote.selectClient': 'Select a client...',
    'quote.isBid': 'Is bidding',
    'quote.executiveAssigned': 'Executive assigned',
    'quote.creada': 'Created',
    'quote.sent': 'Sent',
    'quote.assigned': 'Assigned',
    'quote.quoted': 'Quoted',
    'quote.partialquoted': 'Partial quoted',
    'quote.declined': 'Declined',
    'quote.accepted': 'Acepted',
    'quote.rejected': 'Rejected',
    'quote.cancelled': 'Cancelled',
    'quote.expired': 'Expired',
    'quote.creationDate': 'Creation date',
    'quote.serviceType': 'Service type',
    'quote.loadType': 'Load type',
    'quote.serviceaddtitle': 'No services added',
    'quote.merchaddtitle': 'No merchandise added',
    'quote.serviceaddmessage': 'You must add at least one service to send the quote request.',
    'quote.merchaddmessage': 'You must add at least one item to send the quote request.',
    'quote.accept': 'Accept quotation',
    'quote.cancelrequest': 'Cancel request',
    'quote.reject': 'Reject quotation',
    'quote.reasons': 'Reasons for cancellation',
    'quote.writereasons': 'Write the reasons for cancellation',
    'quote.reasonsreject': 'Reasons for rejection',
    'quote.writereasonsreject': 'Write the reasons for rejection',
    'quote.clone': 'Copied application',
    'quote.modalAutoAssign': 'Executive Assignation',
    'quote.modalAutoAssignQue': 'Do you want to assign this request to yourself?',
    'quote.inputCountryNoOne': 'select a item',
    'quote.inputCountryInvalid': 'select a valid country',
    'exec.title': 'Executive management',
    'exec.newExecutive': 'New executive',
    'exec.editExecutive': 'Edit executive',
    'exec.save': 'Save',
    'exec.cancel': 'Cancel',
    'exec.delete': 'Delete',
    'exec.actions': 'Actions',
    'exec.search': 'Search by name, surname, employee ID or email...',
    'exec.filterAll': 'All',
    'exec.filterActive': 'Active',
    'exec.filterInactive': 'Inactive',
    'exec.nombre': 'First name',
    'exec.apellidoPaterno': 'Last name',
    'exec.apellidoMaterno': 'Second last name',
    'exec.numeroNomina': 'Employee ID',
    'exec.fechaIngreso': 'Hire date',
    'exec.email': 'Email address',
    'exec.departamento': 'Department',
    'exec.activo': 'Active',
    'exec.disponible': 'Active',
    'exec.noDisponible': 'Inactive',
    'exec.generalData': 'Executive information',
    'exec.noResults': 'No executives found',
    'exec.confirmDelete': 'Are you sure you want to delete this executive?',
    'exec.successSave': 'Executive saved',
    'exec.successDelete': 'Executive deleted',
    'exec.errorSave': 'Error saving executive',
    'exec.errorDelete': 'Error deleting executive',
    'exec.errorLoad': 'Error loading executives',
    'exec.nominaExists': 'Employee ID already exists',
    'exec.invalidEmail': 'Invalid email',
    'exec.user': 'User',
    'cust.title': 'Customers',
    'cust.newCustomer': 'New customer',
    'cust.editCustomer': 'Edit customer',
    'cust.save': 'Save',
    'cust.cancel': 'Cancel',
    'cust.delete': 'Delete',
    'cust.search': 'Search customer',
    'cust.generalData': 'General data',
    'cust.addresses': 'Address',
    'cust.contacts': 'Contacts',
    'cust.contact': 'Contact',
    'cust.isBranch': 'Is branch',
    'cust.branchName': 'Branch name',
    'cust.type': 'Person Type',
    'cust.fisica': 'Individual',
    'cust.moral': 'Company',
    'cust.selectPerson': 'Select person',
    'cust.selectCompany': 'Select company',
    'cust.newPerson': 'New person',
    'cust.newCompany': 'New company',
    'cust.nationality': 'Nationality',
    'cust.nacional': 'National',
    'cust.Isnational': 'National',
    'cust.extranjero': 'Foreign',
    'cust.fiscalData': 'Fiscal data',
    'cust.businessName': 'Business name / IMP / EXP',
    'cust.taxId': 'Tax ID',
    'cust.country': 'Country',
    'cust.state': 'State',
    'cust.personName': 'Name',
    'cust.birthDate': 'Birth date',
    'cust.companyName': 'Company name',
    'cust.rfc': 'Tax ID',
    'cust.addContact': 'Add contact',
    'cust.contactType': 'Type',
    'cust.contactName': 'Name',
    'cust.contactEmail': 'Email',
    'cust.contactPhone': 'Phone',
    'cust.contactPosition': 'Position',
    'cust.addAddress': 'Add address',
    'cust.street': 'Street',
    'cust.city': 'City',
    'cust.postalCode': 'Postal code',
    'cust.useRegistered': 'Use registered data',
    'cust.fiscalAddress': 'Fiscal address',
    'cust.noResults': 'No customers found',
    'cust.successSave': 'Customer saved',
    'cust.successDelete': 'Customer deleted',
    'cust.errorSave': 'Error saving customer',
    'cust.errorDelete': 'Error deleting customer',
    'cust.errorLoad': 'Error loading customers',
    'cust.errorMatrizExists': 'This company already has a registered parent customer.',
    'cust.enabled': 'Enabled',
    'cust.actions': 'Actions',
    'cust.TitleDataGeneral': 'General data',
    'cust.checkActive': 'Active',
    'cust.NaturalPerson': 'Natural person',
    'cust.TypeContact': 'Type contact',
    'cust.CompanyName': 'Company name',
    'cust.errorLoadPeople': 'Error loading people',
    'cust.errorLoadCompanyPeople': 'You must select a company or person.',
    'cust.errorLoadcompanies': 'Error loading companies',
    'cust.selectstate': 'Select state',
    'cust.RequiredCompany': 'Select company',
    'cust.selectLevel': 'Select level',
    'cust.RequiredLevel': 'Select company level',
    "cust.clientLevel": "Customer level",
    "cust.clientLevelGold": "Gold",
    "cust.clientLevelSilver": "Silver",
    "cust.clientLevelBronze": "Bronze",
    "cust.isCorrespondent": "Correspondent",
    'comp.errorLoadcompanyRFC': 'You must enter company name and RFC/TAXID.',
    'comp.errorNationality': 'You must select a country for foreign companies.',
    'comp.search': 'Search companies',
    'comp.errorDelete': 'Error deleting company',
    'comp.TitleEdit': 'Edit company',
    'comp.TitleNew': 'New company',
    'comp.SelectCountry': 'Select country',
    'comp.CompanyName': 'Company name',
    'comp.state': 'State',
    'comp.Nacionality': 'Nacionality',
    'comp.Country': 'Country',
    'comp.status': 'Status',
    'comp.Save': 'Save',
    'comp.Cancel': 'Cancel',
    'comp.LoadCompanies': 'Load companies...',
    'comp.Isnational': 'Is national',
    'comp.okupdate': 'Company updated',
    'comp.oksave': 'Company created',
    'comp.DeleteSucess': 'Company deleted',
    'comp.CompanynameRequired': 'Enter company name',
    'comp.RFCTAXIDRequired': 'Enter RFC/TaxID',
    'comp.stateRequired': 'Enter state',
    'supp.title': 'Suppliers',
    'supp.newSupplier': 'New supplier',
    'supp.editSupplier': 'Edit supplier',
    'supp.search' : 'Search supplier, taxid',
    'supp.selectCompany': 'Select company',
    'supp.newCompany': 'New company',
    'supp.IsNational': 'National',
    'supp.IsPersonFisica': 'Natural person',
    'supp.selectSector': 'Select sector',
    'supp.generalData': 'General data',
    'supp.noResults': 'No supplier found',
    'supp.errorSave': 'Error saving supplier',
    'supp.errorDelete': 'Error deleting supplier',
    'supp.save': 'Save',
    'supp.cancel': 'Cancel',
    'supp.contacts': 'Contacts',
    'supp.contact': 'Contact',
    'supp.addContact': 'Add contact',
    'supp.TypeContact': 'Type contact',
    'supp.contactName': 'Name',
    'supp.contactEmail': 'Email',
    'supp.contactPhone': 'Phone',
    'supp.activo': 'Active',
    'supp.addresses': 'Addresses',
    'supp.addAddress': 'Add address',
    'supp.address': 'Address',
    'supp.street': 'Street',
    'supp.city': 'City',
    'supp.state': 'State',
    'supp.postalCode': 'Postal code',
    'nav.catalogs': 'Catalogs',
    'nav.catalogs.imo': 'IMO',
    'nav.catalogs.incoterms': 'Incoterms',
    'nav.catalogs.services': 'Services',
    'nav.catalogs.status': 'Status',
    'nav.catalogs.requestTypes': 'Request types',
    'nav.catalogs.requestType': 'Request type',
    'nav.catalogs.countries': 'Countries',
    'nav.catalogs.country': 'Country',
    'nav.catalogs.sectorOfBusiness': 'Sector of business',
    'nav.catalogs.companies': 'Companies',
    'nav.catalogs.users': 'Users',
    'nav.catalogs.clauses': 'Clauses',
    'catalog.title': '{name} Catalog',
    'catalog.new': 'New {name}',
    'catalog.edit': 'Edit {name}',
    'catalog.save': 'Save',
    'catalog.saving': 'Saving...',
    'catalog.cancel': 'Cancel',
    'catalog.continue': 'Continue',
    'catalog.delete': 'Delete',
    'catalog.search': 'Search...',
    'catalog.actions': 'Actions',
    'catalog.noResults': 'No results found',
    'catalog.confirmDelete': 'Are you sure you want to delete this record?',
    'catalog.successSave': 'Record saved',
    'catalog.successDelete': 'Record deleted',
    'catalog.errorSave': 'Error saving record',
    'catalog.errorDelete': 'Error deleting record',
    'catalog.errorLoad': 'Error loading data',
    'catalog.errorUpdate': 'Error updating record',
    'catalog.optional': '(Optional)',
    'catalog.imo.code': 'IMO Code',
    'catalog.imo.description': 'Description',
    'catalog.incoterm.code': 'Incoterm',
    'catalog.service': 'Service',
    'catalog.service.name': 'Service name',
    'catalog.service.category': 'Category',
    'catalog.service.categoryMain': 'Main',
    'catalog.service.categoryAccessory': 'Accessory',
    'catalog.service.email': 'Email',
    'catalog.requestType.name': 'Request type',
    'catalog.status.category': 'Category',
    'catalog.status.subcategory': 'Subcategory',
    'catalog.status.code': 'Code',
    'catalog.status.name': 'Name',
    'catalog.status.description': 'Description',
    'catalog.status.active': 'Active',
    'catalog.status.inactive': 'Inactive',
    'catalog.filterAll': 'All',
    'catalog.filterActive': 'Active',
    'catalog.filterInactive': 'Inactive',
    'catalog.country.code': 'Country code',
    'catalog.country.name': 'Country name',
    'catalog.sectorOfBusiness.name': 'Sector name',
    'catalog.sectorOfBusiness.description': 'Description',
    'catalog.requiredFields': 'Please fill in all required fields',
    'catalog.exists': 'This {name} already exists.',
    'catalog.clause.tags': 'Tags',
    'catalog.clause.title': 'Title',
    'catalog.clause.es': 'Clause',
    'catalog.clause.en': 'Clause (English)',
    'ctrlpricing.title': 'Pricing controls',
    'ctrlpricing.refresh': 'Refresh',
    'ctrlpricing.filtro': 'Filters',
    'ctrlpricing.actions': 'Actions',
    'ctrlpricing.search': 'Search request',
    'ctrlpricing.edit': 'Edit',
    'ctrlpricing.delete': 'Delete',
    'ctrlpricing.addcontrol': 'Add control number',
    'ctrlpricing.norequests': 'No requests available',
    'ctrlpricing.noresults': 'No results were found with the filters applied.',
    'ctrlpricing.noresultsstatus': 'There are no requests with a status greater than or equal to 3',
    'ctrlpricing.servicesattended': 'Services attended',
    'ctrlpricing.unassigned': 'Unassigned',
    'ctrlpricing.editcontrolnumber': 'Edit control number',
    'ctrlpricing.newcontrolnumber': 'New control number',
    'ctrlpricing.save': 'Save',
    'ctrlpricing.export': 'Export', 
    'ctrlpricing.duplicate': 'Duplicate',
    'ctrlpricing.historical': 'Historical',
    'ctrlpricing.priority': 'Priority',
    'ctrlpricing.bidding': 'Bidding',
    'ctrlpricing.decline': 'Decline',
    'ctrlpricing.quoted': 'Quoted',
    'ctrlpricing.supplierassignment': 'Supplier assignment',
    'ctrlpricing.supplier': 'Supplier',
    'ctrlpricing.suppliername': 'Supplier name',
    'ctrlpricing.addsupplier': 'Add supplier',
    'ctrlpricing.status': 'Status',
    'ctrlpricing.network': 'Network / Alliance',
    'ctrlpricing.complexity': 'Complexity',
    'ctrlpricing.currency': 'Currency',
    'ctrlpricing.unitprofit': 'Unit profit',
    'ctrlpricing.volume': 'Volume',
    'ctrlpricing.generalprofit': 'General profit',
    'ctrlpricing.comments': 'Comments',
    'ctrlpricing.services': 'Services',
    'ctrlpricing.serviceincluded': 'Service included',
    'ctrlpricing.alreadyused': 'Already used in another controller',
    'ctrlpricing.includeservice': 'Include service',
    'ctrlpricing.service': 'Service',
    'ctrlpricing.operation': 'Operation',
    'ctrlpricing.expecteddeparture': 'Expected departure',
    'ctrlpricing.origin': 'Origin',
    'ctrlpricing.destination': 'Destination',
    'ctrlpricing.cpo': 'Origin zip code',
    'ctrlpricing.cpd': 'Destination zip code',
    'ctrlpricing.shippingtype': 'Shipping type',
    'ctrlpricing.associatedServices': 'Associated services',
    'ctrlpricing.noassociatedservices': 'No associated services',
    'ctrlpricing.nocomments': 'No comments',
    'ctrlpricing.programFrequency': 'Schedule frequency',
    'ctrlpricing.frequency': 'Frequency',
    'ctrlpricing.quantity': 'Quantity',
    'ctrlpricing.unit': 'Unit',
    'ctrlpricing.commodity': 'COMMODITY',
    'ctrlpricing.dangerous': 'DANGEROUS',
    'ctrlpricing.classification': 'CLASSIFICATION',
    'ctrlpricing.stackable': 'STACKABLE',
    'ctrlpricing.totalVolume': 'TOTAL VOL',
    'ctrlpricing.totalWeight': 'TOTAL WEIGHT',
    'ctrlpricing.refineSearch': 'Refine your search',
    'ctrlpricing.requestdate': 'Request date',
    'ctrlpricing.today': 'Today',
    'ctrlpricing.yesterday': 'Yesterday',
    'ctrlpricing.less5days': 'Less 5 days',
    'ctrlpricing.less30days': 'Less 30 days',
    'ctrlpricing.less365days': 'Less 365 days',
    'ctrlpricing.assignedexecutive': 'Assigned executive',
    'ctrlpricing.all': 'All',
    'ctrlpricing.onlyme': 'Only me',
    'ctrlpricing.select': 'Select',
    'ctrlpricing.selectexecutive': 'Select executive...',
    'ctrlpricing.selectprov': 'You must select a provider',
    'ctrlpricing.documents': 'Documents',
    'ctrlpricing.portO': 'Origin Port',
    'ctrlpricing.portD': 'Destination Port',
    'ctrlpricing.airportO': 'Origin Airport',
    'ctrlpricing.airportD': 'Destination Airport',
    'ctrlpricing.provalreadyadded': 'This supplier has already been added',
    'ctrlpricing.selectnetwork': 'You must select a network/alliance',
    'ctrlpricing.capturevolume': 'You must capture the volume to calculate the overall profit',
    'ctrlpricing.customercorrespondent': 'Correspondents Client',
    'ctrlpricing.customerlead': 'Lead Client',
    'ctrlpricing.affair': 'Affair',
    'ctrlpricing.cityo': 'City of origin',
    'ctrlpricing.cityd': 'City of destination',
    'ctrlpricing.generateSaleRate': 'Sales rate',
    'tracking.title': 'Tracking Monitor',
    'tracking.subtitle': 'Track your containers in real time',
    'user.title': 'Users',
    'user.newUser': 'New user',
    'user.editUser': 'Edit user',
    'user.save': 'Save',
    'user.cancel': 'Cancel',
    'user.delete': 'Delete',
    'user.actions': 'Actions',
    'user.search': 'Search by name, surname or email...',
    'user.filterAll': 'All',
    'user.filterAdmins': 'Administrators',
    'user.filterActive': 'Active',
    'user.filterInactive': 'Inactive',
    'user.name': 'Name',
    'user.fullName': 'Full name',
    'user.email': 'Email',
    'user.departamento': 'Department',
    'user.roles': 'Roles',
    'user.user': 'User',
    'user.activo': 'Active',
    'user.errorLoad': 'Error loading  users',
    'user.successSave': 'User saved',
    'user.errorSave': 'Error saving user',
    'user.successDelete': 'User deleted',
    'user.errorDelete': 'Error deleting user',
    'user.noResults': 'No users found',
    'user.password': 'Password',
    'user.created': 'Created',
    'user.admin': 'Administrator',
    'modal.title': 'This {name} is about to be deleted.',
    'modal.message': 'Do you wish to continue with the removal?',
    'filter.restore': 'Restore',
    'filter.done': 'Done',
	  'dash.title': 'Dashboard',
	  'dash.subtitle': 'Monitoring customer performance and quote statuses.',
	  'dash.CustomerCategorization':'Customer Categorization',
	  'dash.CustomerCategorization.total': 'Total {count} customer ',
	  'dash.quotationrequest': 'Quotation request',
	  'dash.statementofContributions': 'Statement of Contributions',
	  'dash.quotes.urgent': 'Urgent Quotes',
	  'dash.quotes.recent': 'Recent Quotes',
	  'dash.quotes.records': 'Showing {record} of {records} records',
	  'dash.table.col.client': 'Client',
	  'dash.table.col.type': 'Type',
	  'dash.table.col.expiration': 'Expiration',
    'dash.table.col.status':'Status',
	  'dash.table.col.actions': 'Actions',
	  'dash.table.viewDetail': 'Detail',
	  'dash.performanceperchannel.title':'Performance by channel',
	  'dash.performanceperchannel.subtitle':'Applications Accepted',
	  'dash.performanceperchannel.adress':'Address', 
    'dig.title' :'Digitization',  
    'dig.refineSearch': 'Refine your search',
    'dig.reference': 'Reference',
    'dig.section': 'Section',
    'dig.documentType': 'Document Type',
    'dig.all': 'All',
    'dig.restore': 'Restore',
    'dig.apply': 'Apply',
    "dig.searchDocument": "Search by document, quote reference or customer...",
    'dig.recentFiles': 'Recently uploaded files...',
    'dig.selectAll': 'Select all',
    'dig.unselectAll': 'Unselect all',
    'dig.selected': 'selected',
    'dig.download': 'Download',
    'dig.downloadfiles': 'Download files',
    'dig.downloadfile': 'Download file',
    'dig.delete': 'Delete',
    'dig.noResults': 'No results found',
    'dig.uploadDocuments': 'Upload documents',
    'dig.dragFiles': 'Drag files here',
    'dig.clickToSelect': 'or click to select from your computer',
    'dig.fileType': 'Document type',
    'dig.upload': 'Upload file',
    'dig.uploading': 'Uploading files...',
    'dig.cancel': 'Cancel',
    'dig.refresh': 'Refresh',
    'dig.filters': 'Filters',
    'dig.uploadFiles': 'Upload files',
    'dig.deleteDocument': 'Delete document',
    'dig.deleteDocumentConfirm': 'Do you want to delete "{{name}}"?',
    'dig.deleteSuccess': 'Document deleted successfully',
    'dig.deleteError': 'Error delete document',
    'dig.deleteDocuments': 'Delete documents',
    'dig.deleteDocumentsConfirm': 'Delete {{count}} selected documents?',
    'dig.deleteDocumentsSuccess': 'Documents deleted successfully',
    'dig.referenceRequired': 'You must enter a reference',
    'dig.downloadError': 'Error downloading file',
    'dig.downloadFailed': 'File could not be downloaded',
    'dig.catalogError': 'No information found',
    'dig.uploadValidation': 'You must fill reference, document type and section',
    'dig.uploadError': 'Error uploading files',
    'dig.uploadCanceled': 'Upload canceled',
    'dig.uploadingFiles': 'Uploading {{count}} file(s)...',
    'dig.uploadFilesCount': 'Upload {{count}} file(s)',
    'dig.uploadFile': 'Upload file',
    'dig.selectedFiles': 'Selected files',
    'dig.searchReference': 'Reference',
    'dig.fileDownloaded': 'File {{name}} downloaded',
    'dig.zipDownloaded': '{{count}} files downloaded in ZIP',
    'dig.downloadFilesError': 'Error downloading files',
    'dig.fileUploaded': 'File {{name}} uploaded',
    'dig.fileUploadError': 'Error uploading {{name}}',
    'dig.documents': 'Documents',
    'dig.ErrorGetDocumentsByReference': 'Error loading documents by reference',
    "dig.noReference": "The request has no reference",
    "dig.noDocuments": "No documents available to download",
    "dig.invalidDocument": "Invalid document",
    "dig.cannotDelete": "Cannot delete document",
    "dig.documentHasAcceptedRate": "You cannot delete this document because it has a rate accepted by the customer",
    "dig.documentHasAcceptedRateSingle": "The document cannot be deleted because it has been accepted by the client",
    "dig.documentHasAcceptedRateMultiple": "You cannot delete {{count}} documents because they have been accepted by the client",
    "dig.OKmodal": "Ok",
    "tvf.title": "Quoted rate",
    "tvf.subtitle": "Pricing control",
    "tvf.subtitleGeneral": "General",
    "tvf.Draft": "Draft",
    "tvf.LanguageFormat": "Language format",
    "tvf.LanguageSpanish": "Spanish",
    "tvf.LanguageEnglish": "English",
    "tvf.Preview": "Preview",
    "tvf.ViewRate": "View rate",
    "tvf.ExecutiveInCharge": "Account executive",
    "tvf.QuoteRequestRef": "Quotation request reference",
    "tvf.Quota": "# Quoted",
    "tvf.Version": "Version # ",
    "tvf.OfferValidity": "Offer validity",
    "tvf.Services": "Services",
    "tvf.Export": "Export",
    "tvf.Import": "Import",
    "tvf.DoorToPort": "Door to Port",
    "tvf.LogisticRoute": "Logistics route",
    "tvf.PortOfOrigin": "Port of origin",
    "tvf.PortOfDestination": "Port of destination",
    "tvf.CargoSummary": "Cargo summary",
    "tvf.Goods": "Goods",
    "tvf.AssociatedServices": "Associated services",
    "tvf.Concepts": "Concepts",
    "tvf.AdditionalNotesComments": "Additional notes and comments",
    "tvf.TermsConditions": "Terms and conditions",
    "tvf.SubtotalAmount": "Subtotal amount",
    "tvf.EstimatedTaxVAT": "Estimated tax (VAT)",
    "tvf.TotalAmount": "Total amount",
    "tvf.SearchOrAddTerms": "Search or add terms...",
    "tvf.MaritimeConcepts": "Maritime concepts",
    "tvf.AirConcepts": "Air concepts",
    "tvf.AirOperationalConcepts": "Air operational concepts",
    "tvf.LandConcepts": "Land concepts",
    "tvf.currency": "Currency",
    "tvf.currencyConversion": "Currency conv.",
    "tvf.ExchangeRate": "Exchange",
    "tvf.Generate": "Generate",
    "tvf.AddNewConcept": "Add concept",
    "tvf.Maritime": "Maritime",
    "tvf.Air": "Air",
    "tvf.Land": "Land",
    "tvf.BreakdownByCharges": "Breakdown by charges",
    "tvf.Charge": "Charge",
    "tvf.Subtotal": "Subtotal",
    "tvf.VAT": "VAT",
    "tvf.Total": "Total",
    "tvf.Concept": "Concept",
    "tvf.Base": "Base",
    "tvf.Container": "Container",
    "tvf.Unit": "Unit",
    "tvf.Actions": "Actions",
    "tvf.Airline": "Airline",
    "tvf.Route": "Route",
    "tvf.Transit": "Transit",
    "tvf.RateKG": "Rate/KG",
    "tvf.FCS": "FCS",
    "tvf.SSC": "SSC",
    "tvf.MCC": "MCC",
    "tvf.CW": "CW",
    "tvf.ConsultingServicesConcepts": "Accessory concepts",
    "tvf.noQuote": "No quote",
    "tvf.Advisory": "Accesorial",
    "tvf.GenerateOK": "Quoted rate generated successfully, quoted number: ",
    "tvf.GenerateError": "Error generating the quoted rate",
    "tvf.UpdateOK": "Sales rate updated",
    "tvf.UpdateStatusError": "An error occurred while updating the sales rate status",
    "tvf.UpdateError": "An error occurred while updating the sales rate",
    "tvf.UpdateStatusControlOK": "Control status updated successfully",
    "tvf.UpdateStatusControlError": "An error occurred while updating the control status",
    "tvf.SinConceptos": "No concepts",
    "tvf.Origen": "Origin",
    "tvf.Destino": "Destination",
    "tvf.TermsPlaceholder": "Type or paste the terms and conditions...",
    "tvf.Elegir": "Select",
    "tvf.ElegirContenedor": "Select container...",
    "tvf.TotalMustBeGreaterThanZero": "The total amount of the concepts must be greater than zero",
    "tvf.GenerateTitle": "Generate new version",
    "tvf.GenerateConfirmMessage": "A new version #{version} of the quoted will be created. Do you want to continue?",    
    "tvf.NoContacts":"No contacts",
    "tvf.GenerateCancel":"Cancel",
    "tvf.Contact":"Contact",
    "tvf.NoName": "No name",
    "tvf.NoEmail": "No email",
    "tvf.NoPhone": "No phone",
    "tvf.NoCharge":"NO CHARGE",
    "tvf.ContactRequired": "Contact is required",
    "tvf.CurrencyRequired": "Currency is required",
    "tvf.CurrencyToRequired": "Conversion currency is required",
    "tvf.ExchangeRateRequired": "Exchange rate is required",
    "tvf.ValidFromRequired": "The initial validity date is required",
    "tvf.ValidUntilRequired": "The final validity date is required",
    "tvf.RequiredFields": "Required fields",
    "tvf.FieldRequired": "required",
    "tvf.AirOperational": "Air Operational",
    "tvf.termsValueRequired": "Terms and conditions are required",
    "tvf.ValidUntilMustBeGreater": "The end date cannot be earlier than the start date",
    "tvf.WarningTitle": "Status Change Confirmation",
    "tvf.ChangeStatusToDraftMessagept1": "The rate is currently in status ",
    "tvf.ChangeStatusToDraftMessagept2": "It will be updated to Draft. Do you want to continue?",
    "tvf.Confirm": "Confirm",
    "tvf.Cancel": "Cancel",
    "tvf.UpdateToDraft": "Update to draft",
    "tvf.PdfUploadOK": "PDF generated and uploaded successfully",
    "tvf.PdfUploadError": "The document could not be uploaded",
    "tvf.ConceptSubtotalRequired": "Each concept must include a name and an amount greater than 0.",
    "tvf.PdfUploadWarning": "The quote was generated, but the PDF could not be uploaded.",
    "tvf.generatingPdf": "Generating PDF...",
    "tvf.pleaseWait": "Please wait...",
    "tvf.Noaddress": "No address",
    "tvf.enterAddress": "Enter address",
    "tvf.Name": "Name",
    "tvf.Email": "Email",
    "tvf.Phone": "Phone",
    "tvf.NameRequired": "Contact name is required",
    "tvf.EmailRequired": "Contact email is required",
    "tvf.PhoneRequired": "Contact phone is required",
    "tvf.SaveError": "Error saving",
    "tvf.GeneralError": "Error general",
    "tvf.SavedAt": "Saved at ",
    "tvf.ConceptUnValid": "Row {row} contains incorrect numeric data. Please review amounts, units, or charges.",
    "tvf.WithoutFolio": "NoFolio",
    "tvf.Duplicate": "Duplicate",
    "tvf.Delete": "Delete",
    "score.scoreQuotations": "Quotation Score",
    "score.scoreQuotationsResume": "Real-time tracking of the status and performance of the Pricing team in the quotation process.",
    "score.print": "Print",
    "score.totalQuotations": "Quotations Accumulated",
    "score.quotations": "Quotations",
    "score.quotationsPendients": "Pending",
    "score.quotationsAccepted": "Accepted",
    "score.totalQuotationsResume": "Accumulated activity on the platform during the current year ",
    "score.quotationsAcceptedMonth": "Accepted quotations ",    
    "score.individualMetrics": "Individual Score",
    "score.accumulated": "accumulated",
    "report.title": "Reports",
    "report.subtitle": "Select a report to view",
    "report.seartoogle":"Search reports by Clave or Name",
    "report.header1":"Clue",
    "report.header2":"Category",
    "report.header3":"Name",
    "report.header4":"Description",    
    "report.header5":"Creador",
    "report.header6":"Record",
    "report.titleparameter":"Configured report parameters",
    "report.subtitleparameter":"Refine the scope of the data for the summary.",
    "report.button": "Generate Results",
    "report.filter": "More filters",
    "report.show": "Show",
    "report.show2": "reports",
    "report.show3": "records",
    "report.show4": "of",
    "report.titleresult":"Query Results",
    "report.generatedby":"Generated by",
    "report.generationdate":"Generation Date",
    "report.mesage1":"You must capture at least one parameter to generate the report.",
    "report.mesage2":"The report did not generate results with the parameters provided.",
    "operations.title": "Operations",
    "operations.search": "Search by reference, client, or pricing control...",
    "operations.newOperation": "New operation",
    "operations.editOperation": "Edit operation",
    "operations.generalData": "General data",
    "operations.services": "Services",
    "operations.merchandise": "Merchandise",
    "operations.reference": "Reference",
    "operations.customer": "Customer",
    "operations.selectCustomer": "Select a client...",
    "operations.controls": "Controls",
    "operations.selectControl": "Select a control...",
    "operations.addControl": "Add control",
    "operations.selectControlWarning": "Please select a control to add",
    "operations.selectService": "Select a service...",
    "operations.addService": "Add service",
    "operations.selectServiceWarning": "Please select a service to add",
    "operations.observations": "Observations",
    "operations.listaparafacturar": "Ready to invoice",
    "operations.countryCharge": "Country Charge",
    "operations.arrivalPlant": "Arrival at plant",
    "operations.portDischarge": "Discharge port",
    "operations.airportDischarge": "Discharge airport",
    "operations.tieneControl": "Does it have a control number?",
    "operations.shipment": "Shipment",
    "operations.mode": "Mode",
    "operations.operationtype": "Operation type",
    "operations.incoterm": "Inconterm",
    "operations.transport": "Transport",
    "operations.carrier": "Carrier",
    "operations.unitType": "Unit type",
    "operations.bookingNumber": "Booking number",
    "operations.bookingDate": "Booking date",
    "operations.unitName": "Unit name",
    "operations.plates": "Plates",
    "operations.routeType": "Route type",
    "operations.plantAppointment": "Plant appointment",
    "operations.movementType": "Movement type",
    "operations.typeGuide": "Type | Guide",
    "operations.origin": "Origin",
    "operations.destination": "Destination",
    "operations.collectionLocation": "Collection location",
    "operations.plantExit": "Plant exit",
  },
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('es');
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    const stored = localStorage.getItem('language') as Language | null;
    if (stored) {
      setLanguage(stored);
    }
    setMounted(true);
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string,
     params?: {
      values?: Record<string, string | number>;
      upper?: boolean;
    }
  ): string => {
    //return translations[language][key as keyof typeof translations['es']] || key;
    let text =
      translations[language][
        key as keyof typeof translations['es']
      ] || key;

    if (params?.values) {
      Object.keys(params.values).forEach((variable) => {
        text = text.replace(
          new RegExp(`{${variable}}`, 'g'),
          String(params.values?.[variable])
        );
      });
    }

    if (params?.upper) {
      text = text.toUpperCase();
    }

    return text;
  };

  if (!mounted) return <>{children}</>;

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
